"use client";

import React, { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Search } from 'lucide-react';

const ClientSquadSearch = () => {
  const [searchTerm, setSearchTerm] = useState('');

  // Sample data structure
  const data = {
    "market": "ASEAN Market",
    "squads": [
      {
        "name": "Indonesia ST-BPS-S1",
        "groups": [
          {
            "id": "T0012333",
            "clients": [
              "AMERICAN EXPRESS BANK LTD",
              "BANK INDONESIA",
              "BANK INDONESIA CABANG SURABAYA",
              "BANK RAKYAT INDONESIA",
              "BPD BALI",
              "BPD JABAR CABANG BOGOR",
              "BPD JABAR CABANG TANGERANG",
              "BRI SYARIAH CABANG JAKARTA",
              "BUT STANDARD CHARTERED BANK",
              "OTORITAS JASA KEUANGAN",
              "PT AGRINUSA JAYA SANTOSA",
              "PT ALLO BANK INDONESIA TBK",
              "PT BANK BJB SYARIAH",
              "PT BANK MEGA TBK",
              "PT BPD JABAR TBK (BANK BJB)",
              "PT BRINGIN GIGANTARA",
              "PT JAPFA COMFEED INDONESIA TBK",
              "PT. BANK MEGA SYARIAH",
              "PT. BANK PEMBANGUNAN DAERAH",
              "PT. BANK RAYA INDONESIA TBK.",
              "PT. BRI MULTIFINANCE INDONESIA",
              "PT. BRINGIN INTI TEKNOLOGI",
              "PT. CIOMAS ADISATWA",
              "PT. SANTOSA AGRINDO",
              "PT. SO GOOD FOOD",
              "STANDARD CHARTERED BANK"
            ]
          },
          {
            "id": "T0012340",
            "clients": [
              "ARYADUTA HOTEL JAKARTA",
              "ASTRA CMG LIFE, PT",
              "ASTRA OTOPARTS TBK, PT",
              "ASURANSI ASTRA BUANA, PT",
              "ASURANSI SINAR MAS",
              "BADAN METEOROLOGI,KLIMATOLOGI,",
              "BADAN PENDAPATAN DAERAH",
              "BADAN URUSAN LOGISTIK RI",
              "BANK NOBU",
              "BANK SINARMAS",
              "BERITA SATU MEDIA HOLDINGS",
              "CBN INDONESIA",
              "DIAN SWASTATIKA SENTOSA, PT",
              "DUTA PERTIWI TBK, PT",
              "EKA HOSPITAL JAKARTA",
              "FAST FOOD INDONESIA",
              "INDOMOBIL FINANCE INDONESIA",
              "INDOMOBIL NIAGA INTERNATIONAL",
              "KEMENTERIAN BADAN USAHA MILIK",
              "KEMENTRIAN NEGARA PEMBANGUNAN",
              "LEMBAGA PENERBANGAN DAN",
              "MEGA FINANCE",
              "PERUM PERHUTANI",
              "PINDO DELI PULP & PAPER MILLS",
              "POLITEKNIK ELEKTRONIKA NEGERI",
              "PT ARARA ABADI",
              "PT ARTOMORO PRIMA",
              "PT ARYA SHINTA FINANCE",
              "PT ASTRA AGRO LESTARI TBK",
              "PT ASTRA DAIHATSU MOTOR",
              "PT ASTRA GRAPHIA",
              "PT ASTRA GRAPHIA INFORMATION",
              "PT ASTRA HONDA MOTOR",
              "PT ASTRA INTERNATIONAL TBK",
              "PT ASTRA-GRAPHIA TBK/AGIT ITBG",
              "PT ASTRATEL NUSANTARA",
              "PT ASURANSI AVIVA INDONESIA",
              "PT BANK INA PERDANA",
              "PT BORNEO INDOBARA",
              "PT BUMI KENCANA EKA SEJAHTERA",
              "PT BUMI SERPONG DAMAI",
              "PT CENTURY BATTERIES INDONESIA",
              "PT CYBERINDO ADITAMA",
              "PT DENSO INDONESIA",
              "PT FEDERAL INTERNATIONAL",
              "PT FIRST MEDIA",
              "PT INDAH KIAT PULP & PAPER TBK",
              "PT INDO LOTTE MAKMUR",
              "PT INDOFOOD SUKSES MAKMUR TBK",
              "PT INDOMARCO ADI PRIMA/PEBAPAN",
              "PT INDONUSA TELEMEDIA",
              "PT LIPPO KARAWACI TBK",
              "PT LIPPO TSK INDONESIA",
              "PT LONDON SUMATRA INDONESIA",
              "PT LONTAR PAPYRUS PULP & PAPER",
              "PT MATAHARI DEPARTMENT STORE",
              "PT MATAHARI PUTRA PRIMA TBK",
              "PT MEGA CENTRAL FINANCE",
              "PT METROPOLITAN RETAILMART",
              "PT MORA TELEMATIKA INDONESIA",
              "PT MULTIPOLAR CORPORATION TBK",
              "PT MULTIPOLAR PERKASA",
              "PT MULTIPOLAR TBK",
              "PT MULTIPOLAR TECHNOLOGY TBK",
              "PT NISSAN MOTOR INDONESIA",
              "PT OKI PULP AND PAPER MILLS",
              "PT PABRIK KERTAS TJIWI KIMIA",
              "PT PAKOAKUINA",
              "PT PAMAPERSADA NUSANTARA",
              "PT PERKEBUNAN NUSANTARA III",
              "PT PERS. DAGANG DAN INDUSTRI",
              "PT PERTANI",
              "PT ROLIMEX KIMIA NUSAMAS",
              "PT SERASI AUTORAYA",
              "PT SILOAM INTERNATIONAL",
              "PT SINARMAS SEKURITAS",
              "PT SMART TELECOM",
              "PT SMARTFREN TELECOM TBK",
              "PT SUGITY CREATIVES",
              "PT SURYA ARTHA NUSANTARA",
              "PT SURYARAYA RUBERRINDO",
              "PT TEBO INDAH",
              "PT TOYOTA ASTRA FINANCIAL",
              "PT TOYOTA ASTRA MOTOR",
              "PT TOYOTA AUTO BODY-TOKAI",
              "PT TRANS COFFEE",
              "PT TRANS CORPORA",
              "PT TRANS RETAIL INDONESIA",
              "PT UNITED TRACTORS",
              "PT UNITED TRACTORS PANDU",
              "PT VISIONET DATA INTERNASIONAL",
              "PT VISIONET INTERNASIONAL",
              "PT. ANTA EXPRESS TOUR & TRAVEL",
              "PT. ASTRA SEDAYA FINANCE",
              "PT. ASTRAGRAPHIA",
              "PT. ASURANSI JIWA ASTRA",
              "PT. ASURANSI UMUM MEGA",
              "PT. CYBERINDO MEGA PERSADA",
              "PT. GOLDEN ENERGY MINES",
              "PT. INDAH KIAT PULP & PAPER",
              "PT. INDOKEPPEL DATACENTRE JKT",
              "PT. INDOLAKTO",
              "PT. INDOMOBIL TRADA NASIONAL",
              "PT. INNOVATE MAS INDONESIA",
              "PT. INTERNUX",
              "PT. ISUZU ASTRA MOTOR",
              "PT. KALIMANTAN PRIMA PERSADA",
              "PT. LINK NET, TBK",
              "PT. MARGA MANDALA SAKTI",
              "PT. MEGA CAPITAL INDONESIA",
              "PT. NESTLE INDOFOOD CITARASA",
              "PT. PURINUSA EKA",
              "PT. PURINUSA EKA PERSADA",
              "PT. SALIM IVOMAS PRATAMA",
              "PT. SALIM IVOMAS PRATAMA, TBK",
              "PT. SINAR MAS AGRO RESOURCES",
              "PT. SINARMAS SENTRA CIPTA",
              "PT. TRANS MEDIA SOSIAL",
              "PT. VAYATOUR",
              "PT.AGRANET MULTICITRA SIBERKOM",
              "PT.VISIONET DATA INTERNASIONAL",
              "SILOAM HOSPITALS GROUP",
              "SINARMAS ENERGY AND MINING",
              "SINARMAS LAND",
              "SUZUKI FINANCE INDONESIA PT",
              "TOYOTA ASTRA FINANCIAL",
              "TRANS ICE, PT",
              "TRANS MART, PT",
              "UNIVERSITAS BRAWIJAYA",
              "UNIVERSITAS DIPONEGORO",
              "UNIVERSITAS HASANUDDIN",
              "UNIVERSITAS INDONESIA-FKM-UKK",
              "UNIVERSITAS PELITA HARAPAN"
            ]
          },
          {
            "id": "T0012343",
            "clients": [
              "BADAN PENYELENGGARA JAMINAN",
              "BAHANA PEMBINAAN USAHA",
              "INDONESIA INVESTMENT AUTHORITY",
              "KUSTODIAN SENTRAL EFEK IND",
              "LEMBAGA PENJAMIN SIMPANAN",
              "PT ASURANSI AIOI INDONESIA",
              "PT ASURANSI BUMI ASIH JAYA",
              "PT ASURANSI CENTRAL ASIA",
              "PT ASURANSI JASA INDONESIA",
              "PT ASURANSI JASA RAHARJA",
              "PT ASURANSI JASARAHARJA PUTERA",
              "PT ASURANSI JIWA ADISARANA",
              "PT ASURANSI JIWA JOHN HANCOCK",
              "PT ASURANSI JIWA KRESNA",
              "PT ASURANSI JIWA TUGU MANDIRI",
              "PT ASURANSI JIWASRAYA",
              "PT ASURANSI KREDIT INDONESIA",
              "PT ASURANSI MSIG INDONESIA",
              "PT ASURANSI SOSIAL ABRI",
              "PT BAHANA ARTHA VENTURA",
              "PT BAHANA SECURITIES",
              "PT BAHANA TCW INVESTMENT",
              "PT BURSA EFEK INDONESIA",
              "PT BUSSAN AUTO FINANCE",
              "PT KARUNIA ALAM SEGAR",
              "PT KLIRING PENJAMINAN EFEK",
              "PT MITSUI INDONESIA",
              "PT PEMERINGKAT EFEK INDONESIA",
              "PT PERMODALAN NASIONAL",
              "PT SARANA MULTI INFRASTRUKTUR",
              "PT TASPEN (PERSERO)",
              "PT. ASURANSI KREDIT INDONESIA",
              "PT. JASA RAHARJA (PERSERO)",
              "PT. MITRA TRANSAKSI INDONESIA",
              "PT. PEFINDO BIRO KREDIT",
              "PT. PEGADAIAN",
              "PT. PEGADAIAN GALERI DUA EMPAT",
              "Select Client BPST - New"
            ]
          },
          {
            "id": "T0012333",
            "clients": [
              "PT. MAYBANK INDONESIA FINANCE"
            ]
          },
          {
            "id": "T0012340",
            "clients": [
              "PT INDIKA ENERGY TBK",
              "PT KIDECO JAYA AGUNG",
              "PT MITRA BAHTERA SEGARA SEJATI",
              "PT. MEDCO INTIDINAMIKA"
            ]
          },
          {
            "id": "T0012343",
            "clients": [
              "AJB BUMI PUTERA 1912",
              "AJB BUMIPUTERA 1912",
              "ASURANSI JIWA BERSAMA",
              "PT COLUMBINDO PERDANA",
              "PT KRESNA GRAHA INVESTAMA, TBK",
              "PT MNC LIFE ASSURANCE",
              "PT. BFI FINANCE INDONESIA\t TBK",
              "PT. BNI LIFE INSURANCE",
              "PT. SARATOGA"
            ]
          }
        ]
      },
      {
        "name": "Indonesia ST-BPS-S2",
        "groups": [
          {
            "id": "T0012334",
            "clients": [
              "BANK DAGANG NEGARA",
              "BANK SYARIAH INDONESIA TBK.",
              "LEMBAGA PEMBIAYAAN EKSPOR",
              "MANDIRI SEKURITAS",
              "PT ASURANSI JIWA INHEALTH",
              "PT BANK MANDIRI (PERSERO)",
              "PT BANK MANDIRI (PERSERO) EKS",
              "PT BANK MANDIRI (PERSERO) TBK",
              "PT BANK MANDIRI TASPEN",
              "PT BANK MUAMALAT INDONESIA",
              "PT MANDIRI AXA GENERAL",
              "PT MULTIPOLAR TECHNOLOGY TBK",
              "PT. BANK DKI",
              "PT. BANK MANDIRI TASPEN POS",
              "PT. MANDIRI TUNAS FINANCE",
              "PT. MANDIRI UTAMA FINANCE"
            ]
          },
          {
            "id": "T0012339",
            "clients": [
              "ADMINISTRASI MEDIKA, PT",
              "AKADEMI TELEKOMUNIKASI",
              "ASDP INDONESIA FERRY",
              "BADAN PENGELOLA TABUNGAN",
              "BUT. SAKA INDONESIA PANGKAH",
              "CNOOC SES LTD",
              "GAGAS ENERGI INDONESIA",
              "INDOSAT MEGA MEDIA",
              "JOB PERTAMINA MEDCO TOMORI",
              "JOB PERTAMINA TALISMAN",
              "MATAHARI LINTAS CAKRAWALA",
              "MEDIATAMA ANUGRAH CITRA, PT",
              "MIDTRANS PT",
              "MNC KABEL MEDIACOM, PT",
              "MULTI ADIPRAKARSA MANUNGGAL",
              "PERTAMINA DIREKTORAT EP",
              "PERTAMINA EP, PT",
              "PERTAMINA UJUNG PANDANG",
              "PERTAMINA UP IV CILACAP",
              "PERTAMINA UP.II DUMAI",
              "PLN 3 PADANG",
              "PLN DISTR 12 JAWA TIMUR",
              "PLN JAYA TANGERANG",
              "PLN MEDAN",
              "PLN PUSDIKLAT",
              "PLN WIL.II MEDAN",
              "PLN/UJUNG PANDANG",
              "PT (PERSERO) GAS NEGARA",
              "PT ABHIMATA CITRA ABADI",
              "PT ABHIMATA PERSADA",
              "PT ANABATIC TECHNOLOGIES",
              "PT ANABATIC TECHNOLOGIES TBK",
              "PT APLIKANUSA LINTASARTA",
              "PT BINAREKA TATAMANDIRI",
              "PT BLUE POWER TECHNOLOGY",
              "PT BUMI SIAK PUSAKO-PERTAMINA",
              "PT COLLEGA INTI PRATAMA",
              "PT COMPUTRADE INDONESIA",
              "PT COMPUTRADE TECHNOLOGY",
              "PT ELNUSA GEOSAINS",
              "PT ELNUSA TBK",
              "PT ELNUSA TELEMATIKA",
              "PT FINNET INDONESIA",
              "PT GLOBAL INFORMASI BERMUTU",
              "PT GRAHA INFORMATIKA NUSANTARA",
              "PT INDONESIA COMNET PLUS",
              "PT INDOSAT TBK",
              "PT INDOSIAR VISUAL MANDIRI",
              "PT INDUSTRI TELEKOMUNIKASI",
              "PT INFOKOM ELEKTRINDO",
              "PT INFOMEDIA NUSANTARA",
              "PT KOMPAS MEDIA NUSANTARA",
              "PT MEDIA NUSANTARA CITRA TBK",
              "PT METRANET",
              "PT METRODATA E BISNIS",
              "PT METRODATA E-BISNIS",
              "PT METRODATA ELECTRONICS",
              "PT METRODATA ELECTRONICS TBK",
              "PT MITRA INFOSARANA",
              "PT MITRA INTEGRASI INFORMATIKA",
              "PT MNC SKYVISION",
              "PT MULTI ADIPRAKARSA MANUNGGAL",
              "PT MULTIMEDIA NUSANTARA",
              "PT PEMBANGKITAN JAWA BALI",
              "PT PEMBANGUNAN JAYA ANCOL TBK",
              "PT PERTAMINA",
              "PT PERTAMINA (PERSERO)",
              "PT PERTAMINA BINA MEDIKA IHC",
              "PT PERTAMINA EP",
              "PT PERTAMINA EPTC",
              "PT PERTAMINA GEOTHERMAL ENERGY",
              "PT PERTAMINA HULU ENERGI",
              "PT PERTAMINA HULU ENERGI OSES",
              "PT PERTAMINA HULU MAHAKAM",
              "PT PERUSAHAAN GAS NEGARA",
              "PT PINS INDONESIA",
              "PT PJB SERVICES",
              "PT PLN (PERSERO) DISTRIBUSI",
              "PT PLN (PERSERO) UBS P3B",
              "PT PLN BATAM",
              "PT PLN(PERSERO)PENYALURAN DAN",
              "PT RAJAWALI CITRA TELEVISI IND",
              "PT REASURANSI INDONESIA UTAMA",
              "PT SIGMA CIPTA CARAKA",
              "PT SIGMA CIPTA UTAMA",
              "PT SIGMA KARYA SEMPURNA",
              "PT SIGMA METRASYS SOLUTIONS",
              "PT SURYA CITRA TELEVISI",
              "PT TELEKOMUNIKASI INDONESIA",
              "PT TELEKOMUNIKASI INDONESIA TB",
              "PT TELEKOMUNIKASI SELULAR -",
              "PT TELKOM AKSES",
              "PT TELKOM INDONESIA TBK PROBIS",
              "PT TUGU PRATAMA INDONESIA",
              "PT XDC INDONESIA",
              "PT. AETERNIT INTERNATIONAL",
              "PT. APLIKANUSA LINTASARTA",
              "PT. COLLEGA INTI PRATAMA",
              "PT. DAYAMITRA TELEKOMUNIKASI",
              "PT. DIGITAL VISION NUSANTARA",
              "PT. GOTO GOJEK TOKOPEDIA",
              "PT. INDONESIA POWER",
              "PT. INDOSAT TBK",
              "PT. INFRASTRUKTUR",
              "PT. KREATIF MEDIA KARYA",
              "PT. LAPI ITB",
              "PT. MEDIA NUSANTARA INFORMASI",
              "PT. NIAGAPRIMA PARAMITRA",
              "PT. PAITON ENERGY",
              "PT. PEMBANGKITAN JAWA BALI",
              "PT. PERTAMINA GAS",
              "PT. PERTAMINA HULU",
              "PT. PERTAMINA HULU ENERGI",
              "PT. PERTAMINA HULU ROKAN",
              "PT. PERUSAHAAN LISTRIK NEGARA",
              "PT. PGAS SOLUTION",
              "PT. PGAS TELEKOMUNIKASI",
              "PT. PLN P2B",
              "PT. TELEKOMUNIKASI INDONESIA",
              "PT. TELEKOMUNIKASI SELULAR",
              "PT. TELKOM DATA EKOSISTEM",
              "PT. TELKOM INDONESIA (PERSERO)",
              "PT. TELTRANET APLIKASI SOLUSI",
              "PT. TRI ADI BERSAMA",
              "PT. WIJAYA KARYA (PERSERO) TBK",
              "PT.BANK RIAU KEPRI",
              "PT.INDONESIA COMNET PLUS",
              "PT.SIGMA METRASYS SOLUTION",
              "PT.TELEKOMUNIKASI SELULAR",
              "SATUAN KERJA KHUSUS PELAKSANA",
              "SINDOTV"
            ]
          },
          {
            "id": "T0012345",
            "clients": [
              "ASURANSI BANGUN ASKRIDA PT",
              "ASURANSI MITRA MAPARYA",
              "ASURANSI RAMAYANA PT TBK",
              "ASURANSI WAHANA TATA, PT",
              "BPJS KESEHATAN",
              "BPJS KETENAGAKERJAAN",
              "PT AJ MANULIFE INDONESIA",
              "PT ASKES (PERSERO)",
              "PT ASURANSI ALLIANZ LIFE IND",
              "PT ASURANSI ALLIANZ UTAMA",
              "PT ASURANSI JIWA SEQUIS",
              "PT ASURANSI JIWA SEQUIS LIFE",
              "PT EASTSPRING INVESTMENTS",
              "PT PRUDENTIAL LIFE ASSURANCE",
              "PT. ASKES (PERSERO)",
              "PT. ASURANSI JIWA SEQUIS",
              "PT. CHUBB GENERAL INSURANCE"
            ]
          },
          {
            "id": "T0012346",
            "clients": [
              "PT AIA FINANCIAL",
              "PT ASURANSI AXA INDONESIA",
              "PT ASURANSI JIWA GENERALI",
              "PT AXA FINANCIAL INDONESIA",
              "PT AXA GROUP OPERATIONS",
              "PT AXA SERVICES INDONESIA",
              "PT CIMB SUN LIFE",
              "PT. AXA LIFE INDONESIA",
              "PT. AXA MANDIRI FINANCIAL",
              "PT. SUN LIFE INDONESIA",
              "PT.SUN LIFE FINANCIAL",
              "Select Client BPST - New"
            ]
          },
          {
            "id": "T0012339",
            "clients": [
              "PT BAKRIE COMMUNICATIONS CORP",
              "PT BUMI RESOURCES TBK",
              "PT GRAMEDIA ASRI MEDIA",
              "PT HIPERNET INDODATA",
              "PT MEDIA TELEVISI INDONESIA",
              "PT. MASTERSYSTEM INFOTAMA",
              "PT. SAT NUSAPERSADA TBK",
              "PT. TOWER BERSAMA"
            ]
          }
        ]
      },
      {
        "name": "Indonesia ST-BPS-S3",
        "groups": [
          {
            "id": "T0012335",
            "clients": []
          },
          {
            "id": "T0012336",
            "clients": [
              "BANK ARTA NIAGA KENCANA",
              "BANK COMMONWEALTH",
              "BANK NAGARI, PT",
              "BANK NUSANTARA PARAHYANGAN",
              "BUT. MUFG BANK, LTD",
              "CIMB SECURITIES INDONESIA PT",
              "CITIBANK N.A",
              "CITIBANK NA (GLOBAL CONSUMER)",
              "JCB CO., LTD",
              "PT BANK ANZ INDONESIA",
              "PT BANK CIMB NIAGA TBK",
              "PT BANK PERMATA TBK",
              "PT BANK UOB BUANA",
              "PT BANK UOB BUANA TBK",
              "PT BANK UOB INDONESIA",
              "PT BANK VICTORIA INTERNATIONAL",
              "PT BTMU - BRI FINANCE",
              "PT CIMB NIAGA AUTO FINANCE",
              "PT CITICORP FINANCE INDONESIA",
              "PT FIRST STATE INVESTMENTS",
              "PT PAN INDONESIA BANK, TBK",
              "PT PANIN DAI-ICHI LIFE",
              "PT UOB KAY HIAN SECURITIES",
              "PT. BANK NIAGA TBK",
              "PT. BANK PANIN",
              "PT. BANK PANIN DUBAI SYARIAH,",
              "PT. BANK PANIN SYARIAH",
              "PT. BANK PERMATA TBK",
              "PT. CITIGROUP SECURITIES",
              "PT. CLIPAN FINANCE INDONESIA",
              "PT. PANIN ASSET MANAGEMENT"
            ]
          },
          {
            "id": "T0012342",
            "clients": [
              "BADAN PENGKAJIAN DAN PENERAPAN",
              "KALBE NUTRITIONALS",
              "KALBIS INSTITUTE CAMPUS",
              "KSO TERMINAL PETIKEMAS KOJA",
              "PERSEROAN TERBATAS",
              "PT  SAMPOERNA TELEKOMUNIKASI",
              "PT (PERSERO) ANGKASA PURA I",
              "PT AERO SYSTEMS INDONESIA",
              "PT ANGKASA PURA II (PERSERO)",
              "PT BHANDA GHARA REKSA",
              "PT BINTANG TOEDJOE",
              "PT CITILINK INDONESIA",
              "PT COCA COLA AMATIL INDONESIA",
              "PT COCA COLA BOTTLING",
              "PT COCA COLA INDONESIA",
              "PT ENSEVAL PUTERA MEGATRADING",
              "PT GARUDA INDONESIA (PERSERO)",
              "PT GARUDA MAINTENANCE FACILITY",
              "PT HANJAYA MANDALA SAMPOERNA",
              "PT KALBE FARMA TBK",
              "PT MITRA ADIPERKASA TBK",
              "PT PANEN LESTARI INTERNUSA",
              "PT PATRA JASA",
              "PT RAJAWALI NUSINDO",
              "PT SAMPOERNA AGRO TBK",
              "PT SAMPOERNA INVESTAMA",
              "PT SAMPOERNA PRINTPACK",
              "PT SAMPOERNA STRATEGIC",
              "PT SAMUDERA INDONESIA TBK",
              "PT SANGHIANG PERKASA",
              "PT SARINAH (PERSERO)",
              "PT SRI REJEKI ISMAN (SRITEX)",
              "PT SUCOFINDO",
              "PT SUMBER GRAHA SEJAHTERA",
              "PT SUPRA BOGA LESTARI",
              "PT TEMPO",
              "PT TEMPO CENTRA MANAGEMENT",
              "PT TEMPO DATA SYSTEM",
              "PT TEMPO SCAN PACIFIC TBK",
              "PT TERMINAL PETIKEMAS SURABAYA",
              "PT. BERSAMA KARUNIA MANDIRI",
              "PT. CREASI MODE INDONESIA",
              "PT. DOM PIZZA INDONESIA",
              "PT. GTECH DIGITAL ASIA",
              "PT. INTEGRASI LOGISTIK CIPTA",
              "PT. MITRA FASHINDO ABADI",
              "PT. MITRAMODE DUTA FASHINDO",
              "PT. NEW PRIOK CONTAINER",
              "PT. OMEGA FASHINDO ADIPERKASA",
              "PT. PERUSAHAAN PERSEROAN (PERS",
              "PT. PHILIP MORRIS SAMPOERNA",
              "PT. PRIMA BUANA PERKASA",
              "PT. SARIMODE FASHINDO",
              "PT. SARIMODE GRIYA",
              "PT. SRIWIJAYA AIR",
              "PT. SUKSES DIVA MANDIRI",
              "PT.MAP AKTIF ADIPERKASA TBK",
              "PT.MITRA SELARAS SEMPURNA",
              "PT.SARI BURGER INDONESIA",
              "PT.SARI COFFEE INDONESIA",
              "RS MITRA KELUARGA",
              "SANGHIANG PERKASA,PT",
              "TERMINAL PETIKEMAS SEMARANG"
            ]
          },
          {
            "id": "T0012344",
            "clients": [
              "BHIRAWA STEEL, PT",
              "BIRO KLASIFIKASI INDONESIA",
              "BUT CHEVRON INDONESIA COMPANY",
              "BUT. CHEVRON GANAL LTD",
              "CHEVRON MAKASSAR LTD",
              "CHEVRON RAPAK LTD",
              "DOK & PERKAPALAN KODJA BAHARI",
              "HONDA PRECISION PARTS",
              "HONDA R&D SOUTHEAST ASIA CO.,",
              "LG ELECTRONICS INDONESIA",
              "PT AISIN INDONESIA",
              "PT ANTAM TBK",
              "PT ASAHIMAS CHEMICAL",
              "PT ASAHIMAS FLAT GLASS TBK",
              "PT ATSUMITEC INDONESIA",
              "PT BARITO PACIFIC TIMBER",
              "PT BRIDGESTONE TIRE INDONESIA",
              "PT CALTEX PACIFIC INDONESIA",
              "PT CHANDRA ASRI PETROCHEMICAL",
              "PT CHEVRON PACIFIC INDONESIA",
              "PT DIAN ABADI PERKASA",
              "PT DOK DAN PERKAPALAN SURABAYA",
              "PT GAJAH TUNGGAL TBK",
              "PT HINO MOTORS MANUFACTURING",
              "PT HINO MOTORS SALES INDONESIA",
              "PT HONDA LOCK INDONESIA",
              "PT HONDA POWER PRODUCTS",
              "PT HONDA PRECISION PARTS",
              "PT HONDA PROSPECT MOTOR",
              "PT HONDA TRADING INDONESIA",
              "PT INDOCEMENT TUNGGAL PRAKARSA",
              "PT LG CNS INDONESIA",
              "PT LG INNOTEK INDONESIA",
              "PT MAGMA NUSANTARA LIMITED",
              "PT MINERAL INDUSTRI INDONESIA",
              "PT MITRA PINASTHIKA MULIA",
              "PT MITRA PINASTHIKA MUSTIKA",
              "PT PAL INDONESIA (PERSERO)",
              "PT PEMBANGUNAN PERUMAHAN",
              "PT PETROKIMIA GRESIK",
              "PT PINDAD (PERSERO)",
              "PT PUPUK INDONESIA (PERSERO)",
              "PT PUPUK ISKANDAR MUDA",
              "PT PUPUK KALIMANTAN TIMUR TBK",
              "PT PUPUK KUJANG",
              "PT SEMEN BATURAJA",
              "PT SEMEN TONASA (PERSERO)",
              "PT SMELTING",
              "PT STYRINDO MONO INDONESIA",
              "PT SURVEYOR INDONESIA",
              "PT TAMBANG BATUBARA BUKIT ASAM",
              "PT TOYO-BESQ PRECISION PARTS",
              "PT TOYOTA MOTOR MANUFACTURING",
              "PT TOYOTA TSUSHO INDONESIA",
              "PT UNOCAL INDONESIA CO",
              "PT YAMAHA INDONESIA MOTOR MFG",
              "PT YAMAHA MOTOR PARTS",
              "PT(PERSERO) WASKITA KARYA",
              "PT. ADHI KARYA (PERSERO) TBK.",
              "PT. ALCAR CHEMCO INDONESIA",
              "PT. CHANDRA ASRI PETROCHEMICAL",
              "PT. COGINDO DAYABERSAMA",
              "PT. DIRGANTARA INDONESIA",
              "PT. INDOCEMENT TUNGGAL",
              "PT. JASA DAYA CHEVRON",
              "PT. JTEKT INDONESIA",
              "PT. MANDAU CIPTA TENAGA",
              "PT. PERTAMINA HULU INDONESIA",
              "PT. SANTOS JAYA ABADI",
              "PT. TIMAH TBK",
              "PT.TD AUTOMOTIVE COMPRESSOR",
              "STAR ENERGY (KAKAP) LTD",
              "STAR ENERGY GEOTHERMAL",
              "STAR ENERGY GEOTHERMAL DARAJAT",
              "STAR ENERGY GEOTHERMAL SALAK,",
              "Select Client BPST - New"
            ]
          },
          {
            "id": "T0012336",
            "clients": [
              "PT BANK ICBC INDONESIA",
              "PT. BANK ICBC INDONESIA"
            ]
          },
          {
            "id": "T0012342",
            "clients": [
              "KALLA GROUP",
              "PT BFI FINANCE INDONESIA TBK",
              "PT BLUE BIRD TBK",
              "PT DINAMIKA USAHAJAYA",
              "PT KHARISMA PEMASARAN BERSAMA",
              "PT LION WINGS",
              "PT MITRA MANDIRI INFORMATIKA",
              "PT SEPATU MAS IDAMAN",
              "PT ULTRAJAYA MILK INDUSTRY &",
              "PT UNILEVER INDONESIA TBK"
            ]
          },
          {
            "id": "T0012344",
            "clients": [
              "BP AMERICA PRODUCTION COMPANY",
              "BP BERAU LTD",
              "BUT. INPEX MASELA, LTD",
              "EXXONMOBIL OIL INDONESIA INC",
              "PT BERAU COAL",
              "PT CIPTA KRIDATAMA",
              "PT DOWELL SCHLUMBERGER INDONES",
              "PT ENERGI MEGA PERSADA TBK",
              "PT ENI INDONESIA",
              "PT ESSO INDONESIA INC",
              "PT FAJAR SURYA WISESA",
              "PT GEOSERVICES",
              "PT INPEX CORPORATION",
              "PT KAO INDONESIA",
              "PT KAO INDONESIA CHEMICALS",
              "PT MEDCO E&P INDONESIA",
              "PT RESWARA MINERGI HARTAMA",
              "PT SCHLUMBERGER GEOPHYSICS NUS",
              "PT SCHLUMBERGER GEOPHYSICSS",
              "PT SEMEN INDONESIA (PERSERO)",
              "PT WESTERNGECO INDONESIA",
              "PT. BERAU COAL ENERGY TBK",
              "PT. BP PETROCHEMICALS",
              "PT. CASTROL INDONESIA",
              "PT. CASTROL MANUFACTURING",
              "PT. DONGGI-SENORO LNG",
              "PT. MEDCO POWER INDONESIA",
              "PT. RIAU ANDALAN PULP & PAPER",
              "PT. SUNGAI BUDI",
              "PT. VARIA USAHA",
              "SAKA FARMA LABORATORIES"
            ]
          }
        ]
      },
      {
        "name": "Indonesia ST-BPS-S4",
        "groups": [
          {
            "id": "T0012337",
            "clients": []
          },
          {
            "id": "T0012338",
            "clients": []
          },
          {
            "id": "T0012347",
            "clients": [
              "BADAN PENGAWASAN KEUANGAN DAN",
              "BADAN PUSAT STATISTIK",
              "BAPPENAS C/O DEPKEU",
              "DEPARTEMEN KEUANGAN RI",
              "DINAS KOMUNIKASI DAN INFORMASI",
              "DINAS KOMUNIKASI DAN INFORMAT-",
              "DINAS KOMUNIKASI DAN INFORMATI",
              "DIREKTORAT JENDERAL",
              "DIREKTORAT JENDERAL ANGGARAN",
              "DIREKTORAT JENDERAL KEKAYAAN",
              "DIREKTORAT JENDERAL PAJAK",
              "DIREKTORAT JENDRAL BEA & CUKAI",
              "DIREKTORAT JENDRAL IMIGRASI",
              "INSTITUT TEKNOLOGI SURABAYA",
              "KEMENTERIAN ENERGI DAN SUMBER",
              "KEMENTERIAN KOMUNIKASI DAN",
              "KEMENTRIAN KEUANGAN",
              "KEMENTRIAN KOMUNIKASI DAN",
              "LEMBAGA PENYIARAN PUBLIK",
              "PARIT PADANG GLOBAL, PT",
              "PELABUHAN I MEDAN",
              "PEMERINTAH KOTA SURABAYA",
              "PERUM LEMBAGA PENYELENGGARA",
              "PERUM PERCETAKAN UANG RI",
              "PT (PERSERO) PELABUHAN",
              "PT (PERSERO) PELABUHAN IND IV",
              "PT ARUN NGL CO",
              "PT BNI MULTIFINANCE",
              "PT INDONESIA LOGISTICS",
              "PT INDUSTRI KERETA API",
              "PT KRAKATAU INFORMATION",
              "PT KRAKATAU STEEL",
              "PT KRAKATAU STEEL (PERSERO)",
              "PT PARIT PADANG",
              "PT PHAPROS",
              "PT(PERSERO) PELABUHAN IND II",
              "PT. ASURANSI JIWA IFG",
              "PT. HUTAMA KARYA (PERSERO)",
              "PT. INDONESIA ASAHAN ALUMINIUM",
              "PT. KRAKATAU POSCO",
              "PT. PELINDO MARINE SERVICES",
              "PT. PELITA AIR SERVICE",
              "PT. PEMBANGUNAN PERUMAHAN",
              "PT. PENJAMINAN INFRASTRUKTUR",
              "PT. POLYTAMA PROPINDO",
              "PT. SEMEN INDONESIA LOGISTIK",
              "PT. SOHO GLOBAL HEALTH",
              "PT. SOHO INDUSTRI PHARMASI",
              "PT.KRAKATAU NIPPON STEEL",
              "PT.PELINDO HUSADA CITRA",
              "RSUD DR. SOETOMO",
              "UNIVERSITAS AIRLANGGA",
              "UNIVERSITAS GAJAH MADA",
              "UNIVERSITAS ISLAM INDONESIA",
              "UNIVERSITAS SEBELAS MARET",
              "UNIVERSITY OF INDONESIA"
            ]
          },
          {
            "id": "T0012348",
            "clients": [
              "BADAN INTELIJEN  NEGARA",
              "BADAN INTELIJEN NEGARA",
              "BADAN NARKOTIKA NASIONAL",
              "BAINTELKAM POLRI",
              "BARESKRIM MABES POLRI",
              "DENSUS 88 AT POLRI",
              "DINAS KESEHATAN DKI",
              "DIREKTORAT LALU LINTAS POLRI",
              "KDPE PEMDA DKI JAYA",
              "KEMENTERIAN HUKUM DAN HAM",
              "KOMISI PEMBERANTASAN KORUPSI",
              "KORLANTAS POLRI",
              "MABAK DISINFOLAHTA",
              "MABES POLRI - PUSINFOLAHTA DIV",
              "MARKAS BESAR KEPOLISIAN NEGARA",
              "PEMERINTAH PROPINSI DKI",
              "PEMERINTAH PROVINSI DKI",
              "PT LRT JAKARTA",
              "PT NVPD SOEDARPO CORPORATION",
              "PT. JAKARTA PROPERTINDO",
              "PT. MASS RAPID TRANSIT JAKARTA",
              "SEKOLAH TINGGI ILMU KEPOLISIAN",
              "UNIVERSITAS BINA NUSANTARA",
              "YAYASAN BINA NUSANTARA",
              "Select Client BPST - New"
            ]
          },
          {
            "id": "T0012338",
            "clients": []
          },
          {
            "id": "T0012347",
            "clients": [
              "BADAN KEPEGAWAIAN NEGARA",
              "BAPEPAM",
              "BKPM",
              "DEPARTEMEN AGAMA REPUBLIK",
              "DEPARTEMEN DALAM NEGERI",
              "DEPARTEMEN PEKERJAAN UMUM RI",
              "DEPARTEMEN TENAGA KERJA RI",
              "DITJEN SUMBER DAYA DAN",
              "KOMISI PEMILIHAN UMUM",
              "KOMISI PEMILIHAN UMUM DAERAH",
              "PEMERINTAH KABUPATEN PASURUAN",
              "PT SANBE FARMA",
              "PT. BINA SAN PRIMA",
              "RUMAH SAKIT KANKER DHARMAIS",
              "RUMAH SAKIT PUSAT ANGKATAN"
            ]
          },
          {
            "id": "T0012348",
            "clients": [
              "BADAN PENGUSAHAAN BATAM",
              "BADAN PERENCANAAN PEMBANGUNAN",
              "BADAN PERTANAHAN NASIONAL",
              "BADAN SAR NASIONAL",
              "DEPARTEMEN PERDAGANGAN",
              "KEMENTERIAN KOPERASI DAN UKM",
              "KEMENTERIAN PEMUDA DAN",
              "MAHKAMAH KONSTITUSI REPUBLIK",
              "SEKOLAH TINGGI ENERGI DAN",
              "UNIVERSITAS ANDALAS"
            ]
          }
        ]
      },
      {
        "name": "Indonesia ST-NCA Squad",
        "groups": [
          {
            "id": "T0012450",
            "clients": [
              "ABADI NIAGA PRIMA",
              "ALP PETRO INDUSTRY",
              "AMAZON WEB SERVICES, INC.",
              "ARTHA TEKNOLOGI",
              "AUSTRALIAN FEDERAL POLICE-",
              "AYANA RESORT & SPA",
              "BADAN KOORD KEL BERENCANA NAS",
              "BADAN PENDAPATAN DAERAH",
              "BADAN PERENCANAAN DAERAH PROVI",
              "BADAN REHABILITASI DAN",
              "BANK AGRIS, PT",
              "BANK CENTRATAMA NASIONAL (CNB)",
              "BANK LIMAN INTERNATIONAL",
              "BANK PEMBANGUNAN DAERAH",
              "BANK PUNDI INDONESIA",
              "BEND.UNIVERSITAS ISLAM NEGERI",
              "BENDAHARA PEMEGANG KAS DINAS",
              "BETHSAIDA HOSPITAL",
              "BEYOND NOW GMBH",
              "BINTAN LAGOON RESORT",
              "BNN SATKER DEPUTI BIDANG",
              "BOGORLIVE PROJECT",
              "BPKP PERWAKILAN PROPINSI",
              "BUT PEARLOIL (TUNGKAL) LTD",
              "CHEMCO HARAPAN NUSANTARA",
              "CIPTO SAPTADJI",
              "CORAL TRIANGLE CENTER",
              "CV ARTA RAYA",
              "CV MAKARYA DUTA RAMA",
              "CV. SINAR BAJA ELECTRIC",
              "DEP KES-DITJEN PELAYANAN MEDIK",
              "DEPARTEMEN PERTANIAN",
              "DINAS KOMUNIKASI DAN",
              "DINAS KOMUNIKASI INFORMATIKA",
              "DINAS PENDAPATAN DAERAH PROV",
              "DINAS PENDAPATAN, PENGELOLAAN",
              "DINAS PENDIDIKAN PROVINSI RIAU",
              "DINAS PENGELOLAAN TEKNOLOGI",
              "DIPENDA TK I JAWA TIMUR",
              "DIPENDA TK.II KUTAI BONTANG",
              "DIPENDA TK.II SLEMAN",
              "DITJEN BIMAS ISLAM URUSAN HAJI",
              "DOUBLETREE BY HILTON JAKARTA",
              "DRACOOLA MULTIMEDIA",
              "DUTA SARANA PERKASA PT",
              "ELECTRONIC CITY INDONESIA PT",
              "EMBASSY OF THE KINGDOM OF",
              "E-MOTION ENTERTAINMENT, PT",
              "EMPORIUM INDONESIA, PT",
              "FAVEO ENTERTAINMENT, PT",
              "GAMETECHNO INDONESIA",
              "GENERAL ELECTRIC FINANCE",
              "HARAPAN BANGSA INTERNATIONAL",
              "HARTONO PLANTATION INDONESIA",
              "HASNUR GROUP",
              "HERMINA GROUP",
              "HIBA UTAMA, PT",
              "IAIN SUMATERA UTARA",
              "IMS HEALTH",
              "INFOTEK JAYA MAKMUR",
              "JAKARTA HILTON HOTEL",
              "JUMBO POWER INTERNATIONAL",
              "KDB DAEWOO SECURITIES",
              "KIWOOM SECURITIES INDONESIA PT",
              "KMI WIRE AND CABLE",
              "KONI PEKANBARU",
              "KOPERASI SIMPAN PINJAM JASA",
              "KRAFT FOOD INDONESIA",
              "LAFARGE BORAL GYPSUM",
              "LKBN ANTARA",
              "LYMAN GROUP",
              "MAYAPADA HOSPITAL",
              "MC DONALD INDONESIA",
              "MEDIA INDONUSA,PT",
              "MEGAXUS INFOTECH, PT",
              "MULTI TRADING PRATAMA",
              "NIPPON INDOSARI",
              "NITTSU LEMO INDONESIA LOGISTIK",
              "NUSA SATU INTI ARTHA, PT",
              "NUSANTARA CAPITAL SECURITIES",
              "ONLINE TRADING ACADEMY",
              "P.T NODEFLUX INDONESIA",
              "PARADOR HOTELS AND RESORTS",
              "PARAMOUNT SERPONG",
              "PD. BPR BANK PASAR KULON PROGO",
              "PDAM SURABAYA",
              "PELABUHAN III UTPK TG PERAK",
              "PELAYARAN FAJARINDO, PT",
              "PEMERINTAH KABUPATEN SLEMAN",
              "PEMERINTAH PROVINSI SULAWESI",
              "PENGELUARAN BAGIAN PENGELOLA",
              "PERSEK.KURNIAWAN, RONAS,",
              "PERUSAHAAN AIR MINUM TANGERANG",
              "PETRONAS NIAGA INDONESIA",
              "PIKSI-INST KEGURUAN I.PENDIDIK",
              "PINEAPPLE CONNECT PTE LTD",
              "POLITEKNIK NEGERI JAKARTA",
              "POLITEKNIK PERTANIAN NEGERI",
              "POLYMATECH INDONESIA",
              "PP DRS PRIJOHANDOJO,",
              "PT  ELECTRONIC DATA",
              "PT 3M INDONESIA",
              "PT 66 PARADISE",
              "PT ABC PRESIDENT INDONESIA",
              "PT AC NIELSEN INDONESIA",
              "PT AECOM INDONESIA",
              "PT AGANSA PRIMATAMA",
              "PT AGRO MAJU RAYA",
              "PT ALSSA CORPORINDO",
              "PT ANEKA INTIPERSADA",
              "PT ANUGRAH JAYA INTI BERSAMA",
              "PT ANUGRAH TEKNOLOGI INDONESIA",
              "PT ARGO MANUNGGAL TEXTILE",
              "PT ARSENAL SAKTI",
              "PT ARTHA TELEKOMINDO",
              "PT ASABA",
              "PT ASIA MOTOR MAKMUR",
              "PT AST INDONESIA",
              "PT ASURANSI RAMA SATRIA WIBAWA",
              "PT ASURANSI TAKAFUL KELUARGA",
              "PT AVANEESH COAL RESOURCES",
              "PT BANK INDONESIA RAYA",
              "PT BANK MUTIARA TBK",
              "PT BEHAESTEX",
              "PT BELFOODS INDONESIA",
              "PT BHUMIREKSA NUSASEJATI",
              "PT BILLITON INDONESIA",
              "PT BINA DATA MANDIRI",
              "PT BINA SAINS CEMERLANG",
              "PT BINUSATIKA",
              "PT BIT TEKNOLOGI NUSANTARA",
              "PT BOEHRINGER INGELHEIM",
              "PT BUNDAMEDIK",
              "PT CAHAYA SAKTI FURINTRACO",
              "PT CATURKARDA DEPO BANGUNAN",
              "PT CHINA COMSERVICE INDONESIA",
              "PT CHINA INSURANCE INDONESIA",
              "PT CHIYODA",
              "PT CIBA VISION BATAM",
              "PT CIPTA SAKSAMA INDONESIA",
              "PT CIPTA SKYNINDO",
              "PT CIPTA WIJAYA MANDIRI",
              "PT COLIBRI NETWORKS",
              "PT CONOCOPHILLIPS INDONESIA",
              "PT CONTINENTAL PANJIPRATAMA",
              "PT CONVERGYS INDONESIA",
              "PT CRODA INDONESIA",
              "PT D&D TECHNOLOGY",
              "PT DATASCRIP",
              "PT DAYA ADIRA MUSTIKA",
              "PT DELTA DJAKARTA TBK",
              "PT DENSO SALES",
              "PT DHANAWIBAWA ARTHA CEMERLANG",
              "PT DINERS JAYA INDONESIA",
              "PT DIRGANTARA PARIPURNA PERSAD",
              "PT DUNKINDO LESTARI",
              "PT DYNAPLAST TBK",
              "PT EAGLE INDO PHARMA",
              "PT EISAI INDONESIA",
              "PT ELECTROLUX INDONESIA",
              "PT ERATEX DJAJA",
              "PT ERICSSON INDONESIA",
              "PT ESSENCE INDONESIA",
              "PT EXPLOITASI ENERGI INDONESIA",
              "PT EXSAMAP ASIA",
              "PT FAJAR MAS MURNI",
              "PT FINANNTARA INTIGA",
              "PT GEMA TEKNOLOGI CAHAYA",
              "PT GEODIS WILSON INDONESIA",
              "PT GITASWARA INDONESIA",
              "PT GLOBAL INTI CORPORATAMA",
              "PT GOODYEAR INDONESIA TBK",
              "PT GRAHA INTI JAYA (JULONG",
              "PT GROWTH ASIA",
              "PT GS BATTERY",
              "PT GUDANG GARAM TBK",
              "PT GUNUNG SUBUR SENTOSA",
              "PT GUTHRIE PECCONINA INDONESIA",
              "PT HAMADEN INDONESIA MFG",
              "PT HATSONSURYA ELECTRIC",
              "PT HOLCIM INDONESIA TBK",
              "PT HUAWEI TECH INVESTMENT",
              "PT INDESSO AROMA",
              "PT INDESSO NIAGATAMA",
              "PT INDOBUANA AUTORAYA",
              "PT INDOBUILDCO",
              "PT INDONESIA NIPPON SEIKI",
              "PT INDOTRUBA TENGAH",
              "PT INET INDONESIA",
              "PT INFO LAB INDONESIA",
              "PT INFOGRAM TELEMEDIA",
              "PT INFOSYS SOLUSI TERPADU",
              "PT INFRACOM TECHNOLOGY",
              "PT ING LIFE INDONESIA",
              "PT INTERDATA BHAKTI MULYA",
              "PT INTI DUFREE PROMOSINDO",
              "PT INTRACO PENTA",
              "PT JAKARTA CAKRATUNGGAL STEEL",
              "PT JASAMEDIKA SARANATAMA",
              "PT JATIS SOLUTIONS ECOM",
              "PT JUSTUS KIMIARAYA",
              "PT JVC ELECTRONICS INDONESIA",
              "PT JVC INDONESIA",
              "PT KALINGGA KENCANA",
              "PT KALTIM METHANOL INDUSTRI",
              "PT KARYA PACIFIC SHIPPING",
              "PT KEONG NUSANTARA ABADI",
              "PT KINERJA INDONESIA",
              "PT KNAUF GYPSUM INDONESIA",
              "PT KODECO ENERGY CO LTD",
              "PT KOLON INA",
              "PT KOMATSU FORGING INDONESIA",
              "PT KOMATSU INDONESIA",
              "PT KOMATSU MARKETING AND",
              "PT KOMATSU UNDERCARRIAGE",
              "PT KORINDO ARIABIMA SARI",
              "PT KSB INDONESIA",
              "PT LABERSA HUTAHAEAN",
              "PT LADANGRUMPUN SUBURABADI",
              "PT LAHAN TANI SAKTI",
              "PT LANGGENG MUARAMAKMUR",
              "PT LEARNING RESOURCES",
              "PT LINC SOLUTIONS",
              "PT LOGAM SARI BEARINDO",
              "PT MAHAKAM SUMBER JAYA",
              "PT MAJU RAYA SEJAHTERA",
              "PT MASPION",
              "PT MASTER WEB NETWORK",
              "PT MATAHARI KAHURIPAN",
              "PT MCDERMOTT INDONESIA",
              "PT MEKAR ARMADA JAYA",
              "PT MENTARI PERSADA AGUNGMAS",
              "PT MERKLE INOVASI TEKNOLOGI",
              "PT METRA DIGITAL MEDIA",
              "PT MINAMAS GEMILANG",
              "PT MITRA INTEGRASI KOMPUTINDO",
              "PT MITSUBA INDONESIA",
              "PT MITSUBISHI HC CAPITAL AND",
              "PT MITSUI OSK LINES INDONESIA",
              "PT MOBILE-8 TELECOM",
              "PT MURNI SOLUSINDO NUSANTARA",
              "PT NATRA RAYA",
              "PT NETSTAR INDONESIA",
              "PT NEX LOGISTICS INDONESIA",
              "PT NEXT INS INDONESIA",
              "PT NIAGA PRIMA PARAMITRA",
              "PT NIPPON STEEL CONSTRUCTION",
              "PT NIRWANA LESTARI",
              "PT NISSAN MOTOR DISTRIBUTOR",
              "PT NISSAN MOTOR INDONESIA",
              "PT NOVARTIS INDONESIA",
              "PT NUSA HALMAHERA MINERALS",
              "PT NUSA SATU INTI ARTHA",
              "PT NUSANTARA SEJAHTERA RAYA",
              "PT NUSANTARA SYSTEMS INT'L",
              "PT NUSAUTAMA MEDICALINDO",
              "PT NYK LINE INDONESIA",
              "PT OMYA INDONESIA",
              "PT OTOMOTIF MEDIATAMA",
              "PT PACIFIC HEALTHCARE SERVICES",
              "PT PANGGUNG ELECTRIC",
              "PT PARIPURNA SWAKARSA",
              "PT PELITA SAMUDERA SHIPPING",
              "PT PELITA SAMUDERA SHIPPINGTBK",
              "PT PERTAFENIKKI ENGINEERING",
              "PT PETNESIA RESINDO",
              "PT PETROSEA",
              "PT PFIZER INDONESIA",
              "PT PGS NUSANTARA",
              "PT PHAROS INDONESIA",
              "PT PHILIPS INDONESIA",
              "PT PIONEER TRADING CO LTD",
              "PT PLATINUM CERAMICS",
              "PT POLYSINDO EKA PERKASA, TBK",
              "PT PRIMA KARYA SARANA",
              "PT PRISMA GLOBAL SOLUSI",
              "PT PRO SISTIMATIKA AUTOMASI",
              "PT PRODIA WIDYAHUSADA",
              "PT PZ CUSSONS INDONESIA",
              "PT Q2 TECHNOLOGIES",
              "PT RAMAYANA LESTARI",
              "PT RODA SAKTI SURYARAYA",
              "PT RUANG RAYA INDONESIA",
              "PT RUKUN SEJAHTERA TEKNIK",
              "PT SANDOZ INDONESIA",
              "PT SANY INDONESIA MACHINERY",
              "PT SARANA MEDIAJASA",
              "PT SERAPHIM DIGITAL TECHNOLOGY",
              "PT SHOWA INDONESIA MFG",
              "PT SIME INDO AGRO",
              "PT SINAR WAJA INDAH",
              "PT SINERGY INFORMASI PRATAMA",
              "PT SKILL (SUMBER KOMP I.LUHUR)",
              "PT SOLUSI MITRA ANDALAN",
              "PT SOLUSINDO KREASI PRATAMA",
              "PT SPORT GLOVE INDONESIA",
              "PT STANDARD TOYO POLIMER",
              "PT STYRON INDONESIA",
              "PT SUBUR DJAJA DIESINDO",
              "PT SUBUR DJAJA TEGUH",
              "PT SUMMARECON AGUNG TBK",
              "PT SUPRA LUXINDO UTAMA",
              "PT SURA INDAH WOOD INDUSTRIES",
              "PT SURVEY PRIMA SOLUSI",
              "PT SURYA MADISTRINDO",
              "PT SWADAYA ANDIKA",
              "PT SWADHARMA DUTA DATA",
              "PT SYARIKAT TAKAFUL INDONESIA",
              "PT TANITO HARUM",
              "PT TANJUNG ENIM LESTARI",
              "PT TEAC ELECTRONICS INDONESIA",
              "PT TECHNIP INDONESIA",
              "PT TECHNOLAND ARYA UTAMA",
              "PT TIARA ADI KENCANA",
              "PT TOZY SENTOSA",
              "PT TRAKTOR NUSANTARA",
              "PT TRIPUTRA PERSADA RAHMAT",
              "PT TRUBA ALAM MANUNGGAL",
              "PT TUNGGAL MITRA PLANTATIONS",
              "PT ULTRA PRIMA ABADI",
              "PT URC INDONESIA",
              "PT VIRGINIA OIL COMPANY",
              "PT VIRTUAL MEDIA NUSANTARA",
              "PT VISI SOLUSI TEKNOLOGI",
              "PT WESTSIDE AGRITAMA",
              "PT WIRAPANDU SUKSES MAKMUR",
              "PT WISMILAK INTI MAKMUR TBK",
              "PT YAKULT INDONESIA PERSADA",
              "PT YANMAR AGRICULTURAL",
              "PT YANMAR DIESEL INDONESIA",
              "PT YUSEN AIR & SEA SERVICE",
              "PT ZENIUS EDUCATION",
              "PT ZTE INDONESIA",
              "PT. ABBOTT INDONESIA",
              "PT. ABBOTT PRODUCTS INDONESIA",
              "PT. ACTAVIS INDONESIA",
              "PT. AGATE INTERNATIONAL",
              "PT. AMCAPITAL INDONESIA",
              "PT. ANGGADA DUTA WISESA",
              "PT. ANUGERAH TUNGGAL MANDIRI",
              "PT. ARKON PRIMA INDONESIA",
              "PT. ASURANSI JASINDO SYARIAH",
              "PT. BAKRIE TELECOM TBK",
              "PT. BALI TOWERINDO SENTRA TBK",
              "PT. BANK JTRUST INDONESIA, TBK",
              "PT. BANK PERKREDITAN RAKYAT",
              "PT. BANK WINDU KENTJANA",
              "PT. BCCARD ASIA PACIFIC",
              "PT. BEHN MEYER CHEMICALS",
              "PT. BERITAGAR MEDIA DIPANTARA",
              "PT. BUMI AMARTHA TEKNOLOGI",
              "PT. BUMI BERKAH BOGA",
              "PT. CATERPILLAR INDONESIA",
              "PT. CIPTA MAPAN LOGISTIC",
              "PT. CIPTADANA ASSET MANAGEMENT",
              "PT. CITRAKOPRASINDO TANI",
              "PT. CORTEVA AGRISCIENCE",
              "PT. CUSHMAN & WAKEFIELD",
              "PT. DIDANATANECA TEKNOLOGI",
              "PT. DJOJONEGORO C-1000",
              "PT. ERHA ARYA MEDIC",
              "PT. ETERNO SYSTEM INDONESIA",
              "PT. EUPEC INDONESIA",
              "PT. EVERSHINE TEX",
              "PT. FILTECH INDONESIA",
              "PT. GENERASI DIGITAL",
              "PT. GLOBAL COMM NUSANTARA",
              "PT. GRAHA INDISPORT",
              "PT. HANIL JAYA STEEL INDONESIA",
              "PT. HD FINANCE TBK",
              "PT. HEXINDO GEMILANG JAYA",
              "PT. INDO PENTA BUMI PERMAI",
              "PT. INDONESIA WACOAL",
              "PT. INNOVATIVE PLASTIC",
              "PT. JUSTUS SAKTI RAYA",
              "PT. KALTIM POST",
              "PT. KGI SEKURITAS INDONESIA",
              "PT. LATINUSA TBK",
              "PT. LINTAS TEKNOLOGI INDONESIA",
              "PT. LOGISTIK OPTIMISASI",
              "PT. LUCKY INDAH KERAMIK",
              "PT. MAHAKA MEDIA TBK",
              "PT. MALEO CREATIVE",
              "PT. MEDIA INVESTAMA INDONESIA",
              "PT. MEKAR ARMADA JAYA",
              "PT. MERAK JAYA BETON",
              "PT. METROPOLITAN TELEVISINDO",
              "PT. MUGI REKSO ABADI",
              "PT. NSSOL SYSTEMS INDONESIA",
              "PT. NUSANTARA DUTA SOLUSINDO",
              "PT. NUTRIFOOD INDONESIA",
              "PT. OBERTHUR TECHNOLOGIES",
              "PT. PALMA SERASIH TBK",
              "PT. PANCA TEKNOLOGI NUSWANTARA",
              "PT. PANDU PROFESINDO",
              "PT. PANVERTA CAKRAKENCANA",
              "PT. PCDC PROPCO ONE",
              "PT. PETEKA KARYA SAMUDRA",
              "PT. PISMA PUTRA TEXTILE",
              "PT. PRATAPA NIRMALA",
              "PT. PRIAMANAYA ENERGI",
              "PT. PRICOL SURYA",
              "PT. PRISMA GLOBAL SOLUSI",
              "PT. QEON INTERACTIVE",
              "PT. RIKEN INDONESIA",
              "PT. SADHANA",
              "PT. SARI MURNI ABADI",
              "PT. SBA WOOD INDUSTRIES",
              "PT. SENTRA PARAMITRA",
              "PT. SIANTAR MADJU",
              "PT. SOFTNET INDONESIA",
              "PT. SQUARE GATE ONE",
              "PT. STOCKBIT SEKURITAS DIGITAL",
              "PT. STRATEGIC PARTNER SOLUTION",
              "PT. SUMIDEN SINTERED",
              "PT. SUPREME ENERGY RANTAU",
              "PT. SURYA HUTANI JAYA",
              "PT. SURYA PEMENANG",
              "PT. SURYASOFT KONSULTAMA",
              "PT. SUTINDO RAYA MULIA",
              "PT. SYSTEM TREE TECHNOLOGY",
              "PT. TAMTAMA PERKASA",
              "PT. TELADAN PRIMA GROUP",
              "PT. TIGA GLOBAL SEJAHTERA",
              "PT. TIMAS SUPLINDO",
              "PT. TRAINOCATE NETWORKS",
              "PT. TRI WAHANA UNIVERSAL",
              "PT. TRISTAR TRANSINDO",
              "PT. WIJAYA KENCANA PRATAMA",
              "PT. WIRAKARYA SAKTI",
              "PT. XL PLANET",
              "PT. YUSEN LOGISTICS INDONESIA",
              "PT.ALTROS TEKNOLOGI",
              "PT.ENERGI SEJAHTERA MAS",
              "PT.MULTI ARTHA SEJAHTERA ABADI",
              "PT.SNET INDONESIA",
              "PT.SURI TANI PEMUKA",
              "PT.SURYA DONASIN",
              "PT.UNA DARMA INDONESIA",
              "PTP NUSANTARA - IV (PERSERO)",
              "PUSKESMAS KECAMATAN TEBET",
              "RADANA FINANCE",
              "RAJAWALI GROUP CORPORATION",
              "RED STUDIO",
              "RICHLAND LOGISTICS INDONESIA",
              "ROXCEL INDONESIA",
              "ROYAL STANDARD, PT",
              "RS PELNI PETAMBURAN",
              "RSUD DR. MARGONO SOEKARJO",
              "RSUD TARAKAN",
              "RSUP DR. HASAN SADIKIN",
              "RUMAH SAKIT ADI HUSADA UDAAN",
              "RUMAH SAKIT MATA AINI",
              "RUMAH SAKIT OMNI ALAM SUTERA",
              "RUMAH SAKIT SATYA NEGARA",
              "SARANA UNGGUL TRANSPORTINDO",
              "SEKOLAH TINGGI ILMU KESEHATAN",
              "SEKRETARIAT DPR",
              "SEKRETARIAT INSPEKTORAT JENDER",
              "SIRCLO",
              "SUDO MOBILE",
              "SUMBER ALFARIA TRIJAYA TBK",
              "SUNBAY AG",
              "SUNTORY BEVERAGE & FOOD ASIA",
              "SUPER MICRO COMPUTER, INC",
              "SUPERMAL KARAWACI PT",
              "SUTINDO ANUGERAH SEJAHTERA, PT",
              "SYNIVERSE TECHNOLOGIES",
              "THE BRITISH INTERNATIONAL",
              "THE ROYAL BANK OF SCOTLAND NV",
              "TIM NASIONAL PERCEPATAN",
              "TOKO GUNUNG AGUNG",
              "TRANSASIA SECURITIES PT",
              "TRIMERA MEDIA UTAMA",
              "TUNAS RIDEAN TBK",
              "UNIVERSITAS ISLAM NEGERI SUNAN",
              "UNIVERSITAS KATOLIK",
              "UNIVERSITAS MATARAM",
              "UNIVERSITAS MUHAMMADIYAH",
              "UNIVERSITAS NEGERI MAKASSAR",
              "UNIVERSITAS NEGERI MEDAN",
              "UNIVERSITAS NEGERI YOGYAKARTA",
              "UNIVERSITAS NUSA CENDANA",
              "UNIVERSITAS SURYA",
              "WIGO DISTRIBUSI FARMASI, PT",
              "YAY. PENDIDIKAN JAYA",
              "YAYASAN MENARA BHAKTI",
              "YAYASAN PEGURUAN TINGGI",
              "YAYASAN PERGURUAN TINGGI",
              "ZETTA MEDIA",
              "ZHONG XING TELECOM CORPORATION"
            ]
          },
          {
            "id": "T0012451",
            "clients": [
              "ADVANCE TECHNOLOGIES",
              "AGUNG SEDAYU GROUP PT",
              "ARI PANTU",
              "ASIA COLUMBIA HOSPITAL",
              "ASOSIASI SISTEM PEMBAYARAN",
              "ASPEX KUMBONG",
              "AUSTRALIAN EMBASSY JAKARTA",
              "AUTORIDADE NACIONAL DO",
              "BADAN PENDAPATAN DAERAH",
              "BALAI PENELITIAN PERKEBUNAN",
              "BALI HYATT HOTEL",
              "BALI INTERCONTINENTAL RESORT",
              "BANK DUTA",
              "BANK PEMBANGUNAN DAERAH",
              "BANK PEMBANGUNAN DAERAH NUSA",
              "BANK PERKREDITAN RAKYAT JATIM",
              "BELOWCEPEK.COM",
              "BEND. PENGELUARAN RS JANTUNG &",
              "BINA SARANA INFORMATIKA",
              "BIZNET GIO CLOUD",
              "BPKP PROPINSI SULUT",
              "BRAWIJAYA UNIVERSITY",
              "BRISTOL-MYERS SQUIBB INDONESIA",
              "BUSANA APPAREL GROUP",
              "BUT SANTOS (SAMPANG) PTY. LTD",
              "BUT VISA INTERNATIONAL",
              "BUT.PTTEP MALUNDA LIMITED",
              "CEMINDO GEMILANG PT",
              "CENTRAL ASIA FINANCIAL, PT",
              "CENTURY TEXTILE INDUSTRY,PT",
              "CIPTA MORTAR UTAMA",
              "CIPTA MULTI USAHA PERKASA",
              "COLOROBBIA INDONESIA, PT",
              "CONRAD BALI",
              "CV SUKSES MAKMUR BERSAMA",
              "DANKOS LABORATORIES TBK, PT",
              "DEP PENDIDIKAN & KEBUDAYAAN RI",
              "DEPARTEMEN KEHUTANAN RI",
              "DEPARTEMEN PERTANIAN",
              "DEPARTEMEN SOSIAL",
              "DIHARDJA SOFTWARE SOLUTION",
              "DINAS PENDAPATAN DAERAH",
              "DINAS PENDAPATAN DAERAH KOTA",
              "DINAS PENDAPATAN KOTA BANDUNG",
              "DINAS PENDIDIKAN PEMERINTAH",
              "DINAS PENGELOLAAN KEUANGAN",
              "DIPENDA TK II MUSI RAWAS",
              "DIPENDA TK.I JAWA TIMUR",
              "DIREKTORAT PBB",
              "DISPENDA SUMUT",
              "DUTA ANGGADA REALTY TBK, PT",
              "ELECTRONIC SOLUTIONS",
              "ETRADING SECURITIES, PT",
              "FAKULTAS ILMU KOMPUTER UB",
              "FIRST RESOURCES GROUP",
              "GEOTECH SYSTEM INDONESIA",
              "GIESECKE & DEVRIENT INDONESIA",
              "GMB 5B PCD COMPUTER & PROFESSI",
              "GUMCODE IT SOLUTION",
              "HYATT REGENCY SURABAYA",
              "HYATT REGENCY YOGYAKARTA",
              "IFCA CONSULTING INDONESIA",
              "INDOMAS SUSEMI JAYA",
              "INSTITUT TEKNOLOGI TELKOM",
              "INTRASARI RAYA",
              "IPTN",
              "JAYA MANDIRI SUKSES",
              "JAYA PROTEKSINDO SAKTI, PT",
              "KANTOR ARSIP DAN PERPUSTAKAAN",
              "KAROSERI LAKSANA",
              "KEJAKSAAN AGUNG RI",
              "KEMENTERIAN LINGKUNGAN HIDUP",
              "KIA MOTOR",
              "KOPERASI KREDIT CU LANTANG",
              "KOPERASI SIMPAN PINJAM",
              "KUFPEC REGIONAL VENTURES",
              "LASMO KRUENG MANE LIMITED",
              "LINTAS MEDIA DANAWA",
              "MAHANUSA",
              "MAJALAH INVESTOR",
              "MANDARIN ORIENTAL HOTEL",
              "MANDOM INDONESIA",
              "MASSINDO INTERNASIONAL",
              "MEGASARI MAKMUR",
              "MEKAR ARMADA INVESTAMA",
              "METRO BATAVIA, PT",
              "MICHELIN ASIA CO. PTE. LTD",
              "MIDTOWN HOTEL SURABAYA",
              "MIKATASA AGUNG, PT",
              "MUBADALA ENERGY",
              "MURNI TEGUH HOSPITAL",
              "NAV KARAOKE KELUARGA",
              "NOKIA CORPORATION",
              "NURKHOLISAH KUSMIYATI",
              "PACIFIC INTERLINK SDN BHD",
              "PANCA WANA INDONESIA",
              "PAU ILMU KOMPUTER UI",
              "PD.AIR MINUM KAB. DATI II",
              "PDAM KOTA BALIKPAPAN",
              "PDAM PAM JAYA",
              "PELNI HOSPITAL",
              "PEMDA TK.I JAWA BARAT",
              "PEMKOT YOGYA",
              "PERFORMANCE MATERIAL PRODUCTS",
              "PERMATA ENERGY RESOURCE",
              "PERMATA HIJAU SAWIT GROUP",
              "PERWAKILAN BPKP PROV DI",
              "PETRONAS CARIGALI BERHAD LTD",
              "POLITEKNIK NEGERI MEDAN",
              "POLITEKNIK NEGERI SRIWIJAYA",
              "PRAWEDA CIPTAKARSA INFORMATIKA",
              "PT (PERSERO) ASURANSI EKSPOR",
              "PT (PERSERO) PELABUHAN",
              "PT A SCHULMAN PLASTICS",
              "PT ABB SAKTI INDUSTRI",
              "PT ADE TEXTILE INDUSTRY",
              "PT AKR CORPORINDO TBK",
              "PT AKUR PRATAMA",
              "PT ALIANSI LINTAS TEKNOLOGI",
              "PT ALTO NETWORK",
              "PT ALUN",
              "PT AMSTILL SECURITIES",
              "PT AMWAY INDONESIA",
              "PT ANDALAS MEDIA INFORMATIKA",
              "PT ANDREWTANI INDONESIA",
              "PT ANOMALI LINTAS TEKNOLOGI",
              "PT ANUGERAH LANGKAT MAKMUR",
              "PT AQUAFARM NUSANTARA",
              "PT ARGO PANTES",
              "PT ARTHAS ENERGY PETROGAS",
              "PT ASIMETRIS DATA SENTOSA",
              "PT AXIS TELEKOM INDONESIA",
              "PT BAKRIE CAPITAL INDONESIA",
              "PT BALI ANIMASI SOLUSI",
              "PT BANK ANDARA",
              "PT BANK HANVIT INDONESIA",
              "PT BANK HARFA",
              "PT BAYER INDONESIA",
              "PT BERCA GLOBAL ACCESS",
              "PT BERCA HARDAYAPERKASA",
              "PT BERCA SCHINDLER LIFTS",
              "PT BERCA SPORTINDO",
              "PT BERSAMA SEJAHTERA SAKTI",
              "PT BETON ELEMENINDO PERKASA",
              "PT BIROTIKA SEMESTA",
              "PT BUMI MODERN",
              "PT BUMIPUTERA BOT FINANCE",
              "PT CAKRAWALA INTI TEKNOLOGI",
              "PT CHARADE INDONESIA",
              "PT CIPTADANA SEKURITAS",
              "PT CODEPHILE REKADAYA MANDIRI",
              "PT CRYSTAL ANUGERAH ABADI",
              "PT DARYA-VARIA LABORATORIA TBK",
              "PT DATACRAFT INDONESIA",
              "PT DATAMATION PURWANA UTAMA",
              "PT DELAMI GARMENT INDUSTRIES",
              "PT DELCOPRIMA PACIFIC",
              "PT DELOITTE KONSULTAN",
              "PT DENKI INDONESIA",
              "PT DHARMA POLIMETAL",
              "PT DIPA PHARMALABS INTERSAINS",
              "PT DISTRIBUSI SURYA KENCANA",
              "PT DKSH TUNGGAL",
              "PT DUPONT AGRICULTURAL PRODUCT",
              "PT DUTA VISUAL NUSANTARA",
              "PT DUTAPALMA NUSANTARA",
              "PT DWIDAYA INDO EXCHANGE",
              "PT EDI INDONESIA",
              "PT EKA BOGA INTI",
              "PT ENERGI TATA PERSADA",
              "PT ERA MEDIA INFORMASI",
              "PT ETERINDO WAHANATAMA TBK",
              "PT ETHICA INDUSTRI FARMASI",
              "PT EVERGREEN MARINE INDONESIA",
              "PT EVERGREEN SHIPPING AGENCY",
              "PT EXECUTRAIN NUSANTARAJAYA",
              "PT FARMINDO ADIJAYA PERSADA",
              "PT FIRMENICH INDONESIA",
              "PT FIT AND HEALTH INDONESIA",
              "PT FUMIRA",
              "PT GALUH CITARUM",
              "PT GAMYA",
              "PT GAWI MAKMUR KALIMANTAN",
              "PT GE FINANCE INDONESIA",
              "PT GEMA KARYA ABADI",
              "PT GEOTECH SYSTEM INDONESIA",
              "PT GLOBAL PUTRA INTERNATIONAL",
              "PT GLORIA ORIGITA COSMETICS",
              "PT GRAND HYATT JAKARTA",
              "PT GRIYA MIESEJATI",
              "PT HANDAL LOGISTIK NUSANTARA",
              "PT HEINZ ABC INDONESIA",
              "PT HOGY INDONESIA",
              "PT HUMPUSS TERMINAL PETIKEMAS",
              "PT ICI PAINTS INDONESIA",
              "PT IFORTE SOLUSI INFOTEK",
              "PT IMAG INFORMASI SOLUSI",
              "PT IMANI PRIMA",
              "PT INDOGOLD SOLUSI GADAI",
              "PT INDOKEMIKA JAYATAMA",
              "PT INDOMETAL MITRABUANA",
              "PT INDONESIA TORAY SYNTHETICS",
              "PT INDONESIAN CLOUD",
              "PT INDORAMA PETROCHEMICALS",
              "PT INDORAMA POLYESTER",
              "PT INDORAMA VENTURES INDONESIA",
              "PT INDOVEST SECURITIES",
              "PT INDUSTRIAL GASES INDONESIA",
              "PT INOVASI INTI SUKSES",
              "PT INOVIDEA MAGNA GLOBAL",
              "PT INTI DINAMIKA LOGITAMA",
              "PT ISTECH RESOURCES ASIA",
              "PT ITOCHU INDONESIA",
              "PT JAINDO METAL INDUSTRIES",
              "PT JARDINE LLOYD THOMPSON",
              "PT JASA ANGKASA SEMESTA TBK",
              "PT JATELINDO PERKASA ABADI",
              "PT JAYA SEJATI",
              "PT JAYAKUSUMA PERDANA LINES",
              "PT JUI SHIN INDONESIA",
              "PT JURNALINDO AKSARA GRAFIKA",
              "PT KARLIN MASTRINDO",
              "PT KATEXINDO CITRAMANDIRI",
              "PT KENARI DJAJA PRIMA",
              "PT KERISMAS WITIKCO MAKMUR",
              "PT KONIMEX",
              "PT KRESNATEL INDONESIA",
              "PT KURIO",
              "PT KURNIA INSURANCE INDONESIA",
              "PT LAGUNA MANDIRI",
              "PT LIEBHERR INDONESIA PERKASA",
              "PT LOGIKREASI UTAMA",
              "PT M CLASS INDUSTRY",
              "PT MAHAGAYA PERDANA",
              "PT MAINPARK MEDIA INDONESIA",
              "PT MANDIRI INTI PERKASA",
              "PT MARS SYMBIOSCIENCE",
              "PT MASPION ELEKTRONIK",
              "PT MASTER KARYA NUSA",
              "PT MEAD JOHNSON INDONESIA",
              "PT MEDION",
              "PT MERCEDES-BENZ DISTRIBUTION",
              "PT MERCEDES-BENZ INDONESIA",
              "PT MERPATI NUSANTARA",
              "PT MHE-DEMAG INDONESIA",
              "PT MILLENIA INFOKOM TEKNOLOGI",
              "PT MISORI UTAMA",
              "PT MITRA ANEKA REZEKI",
              "PT MITRA INFOSARANA",
              "PT MITSUBISHI KRAMA YUDHA",
              "PT MOLTEN ALUMINIUM PRODUCER",
              "PT MONICA HIJAU LESTARI",
              "PT MULIA INDUSTRINDO",
              "PT MULTI BINTANG INDONESIA TBK",
              "PT MULTI CITRA ABADI",
              "PT NENGGALA KARYA",
              "PT NETTOCYBER INDONESIA",
              "PT NOK INDONESIA",
              "PT NUSANTARA COMPNET",
              "PT PACIFIC TEXINDO INDUSTRY",
              "PT PAKARTI RIKEN INDONESIA",
              "PT PANARUB INDUSTRY",
              "PT PAPERTECH INDONESIA",
              "PT PATA INFORMATIKA NUSANTARA",
              "PT PEGASUS KERAMIK TERBAIK",
              "PT PELAYARAN SAMUDERA SELATAN",
              "PT PIJAR MULYA UTAMA",
              "PT PMB INDONESIA",
              "PT POSMI STEEL INDONESIA",
              "PT PRAKARSA ALAM SEGAR",
              "PT PUPUK SRIWIJAYA/BIRO DPC",
              "PT PUTRAMAS MULIA SANTOSA",
              "PT QUARTEE TECHNOLOGIES",
              "PT QUARTRINDO MARINA",
              "PT QUEST INTERNATIONAL",
              "PT RAMA PERWIRA",
              "PT ROMAN CERAMIC INTERNATIONAL",
              "PT SAJANG HEULANG",
              "PT SALAM PACIFIC INDONESIA",
              "PT SANDIMAS REKSAKERAMIKA",
              "PT SARANAKREASI TEKNOLOGI",
              "PT SATYA GLOBAL MULTI MEDIA",
              "PT SCHERING INDONESIA",
              "PT SDV LOGISTICS INDONESIA",
              "PT SEIWA INDONESIA",
              "PT SIBA SURYA",
              "PT S-IK INDONESIA",
              "PT SINERGI EXIMIUS",
              "PT SIOEN INDONESIA",
              "PT SOHO INDUSTRI FARMASI",
              "PT SOLO MURNI",
              "PT SOLUSI INTEGRASI UTAMA",
              "PT SOLUSI TUNAS PRATAMA TBK",
              "PT SONOCO INDONESIA",
              "PT SONY ELECTRONICS INDONESIA",
              "PT SONY MUSIC ENTERTAINMENT",
              "PT SOT INDO-SOURCING",
              "PT SOUTH PACIFIC VISCOSE",
              "PT STAR SURYA PERKASA",
              "PT SUGIHARTA LESTARINDO",
              "PT SUMBER SETIA ABADI",
              "PT SUMI RUBBER INDONESIA",
              "PT SUNGINTEX",
              "PT SUPERNOVA",
              "PT SURYA TIMUR SAKTI JATIM",
              "PT SURYA TOTO INDONESIA",
              "PT SURYA ZIG ZAG",
              "PT TAKEDA INDONESIA",
              "PT TAKENAKA INDONESIA",
              "PT TAMACO GRAHA KRIDA",
              "PT TEC INDONESIA",
              "PT TECHNO INTERNATIONAL",
              "PT TEGUH SEMPURNA",
              "PT TIDAR KERINCI AGUNG",
              "PT TIGARAKSA SATRIA",
              "PT TIMES PRIMA INDONESIA",
              "PT TK INDUSTRIAL INDONESIA",
              "PT TORAY INDUSTRIES INDONESIA",
              "PT TOSHIBA CONSUMER PRODUCT",
              "PT TRIMEGAH SECURITIES TBK",
              "PT TS TECH INDONESIA",
              "PT UPS CARDIG INTERNATIONAL",
              "PT USAHATAMA SENTOSA MAS",
              "PT USI JAYA/CIRCA",
              "PT UTAMA CHIP KOMPUTER",
              "PT VENETA INDONESIA",
              "PT WHIZFONE INDONESIA",
              "PT WYNNCOR BALI",
              "PT. ABSOLUT REALITAS SOLUSI",
              "PT. ADHIMIX PRECAST INDONESIA",
              "PT. ADPLUS DIGITAL SOLUSINDO",
              "PT. ADYABUANA PERSADA",
              "PT. AETRA AIR JAKARTA",
              "PT. AGIVA INDONESIA",
              "PT. ALTRAK 1978",
              "PT. AMTEK ENGINEERING BATAM",
              "PT. APLIKASI KARYA ANAK BANGSA",
              "PT. ARJUNA UTAMA KIMIA",
              "PT. ASTARI NIAGARA",
              "PT. AUSTINDO KENCANA JAYA",
              "PT. BDO KONSULTAN INDONESIA",
              "PT. BERLINA SURABAYA TBK",
              "PT. BIROTIKA SEMESTA / DHL",
              "PT. BIZZY COMMERCE INDONESIA",
              "PT. BUBU KREASI PERDANA",
              "PT. BURSA BERJANGKA JAKARTA",
              "PT. CAKRAWALA PRIMA ENERGI",
              "PT. CERTA SYSTEMS INDONESIA",
              "PT. CITRA BORNEO UTAMA TBK",
              "PT. DANATAMA MAKMUR",
              "PT. DATACARAKA SOLUSINDO",
              "PT. DATANG DSSP POWER",
              "PT. DHARMA SATYA NUSANTARA",
              "PT. DIA ELECTRO CIRCUIT",
              "PT. EASTERN PEARL FLOUR MILLS",
              "PT. EIGERINDO MULTIPRODUK",
              "PT. EIRTEIC CONSULTING ASEAN",
              "PT. EQUNIX BUSINESS SOLUTIONS",
              "PT. ERAJAYA SWASEMBADA TBK",
              "PT. ETHICA INDUSTRI FARMASI",
              "PT. FLUOR DANIEL INDONESIA",
              "PT. FUJITSU INDONESIA",
              "PT. GLOBAL TEKNOLOGI MEDIA",
              "PT. GOLDEN DOLBE",
              "PT. HAIER ELECTRICAL",
              "PT. HARMONI PANCA UTAMA",
              "PT. HOLI PHARMA",
              "PT. HOLLAND COLOURS ASIA",
              "PT. HOME CREDIT INDONESIA",
              "PT. HONDA LOGISTICS INDONESIA",
              "PT. INDO ARTHA TEKNOLOGI",
              "PT. INDOCYBER GLOBAL TEKNOLOGI",
              "PT. INDOFARMA (PERSERO) TBK",
              "PT. INDONESIA CHINA MOBILE",
              "PT. INGENICO INTERNATIONAL",
              "PT. INLAND TELEMATIKA",
              "PT. INSPIRASI TEKNOLOGI",
              "PT. INTI TELADAN ARTHA SWADAYA",
              "PT. INTILAND DEVELOPMENT, TBK",
              "PT. JADDI GLOBAL SEJAHTERA",
              "PT. KINO INDONESIA TBK",
              "PT. KMK GLOBAL SPORTS",
              "PT. KREDIT BIRO INDONESIA JAYA",
              "PT. LAMIPAK PRIMULA INDONESIA",
              "PT. MAHAVIRA SYSTEM INTEGRA",
              "PT. MAUKU INDONESIA ABADI",
              "PT. MC LIVING ESSENTIALS",
              "PT. MEDIA INVESTOR INDONESIA",
              "PT. MEDIXSOFT",
              "PT. MEINDO ELANG INDAH",
              "PT. MIRAE ASSET SEKURITAS",
              "PT. MOBILE COIN ASIA",
              "PT. NAP INFO LINTAS NUSA",
              "PT. NOKIA SIEMENS NETWORKS",
              "PT. NOVELL PHARMACEUTICAL",
              "PT. NUSANTARA SURYA SAKTI",
              "PT. PANCARAN DARAT TRANSPORT",
              "PT. PARAGON PRATAMA TEKNOLOGI",
              "PT. PARAGON UNIVERSA UTAMA",
              "PT. PENTA VALENT",
              "PT. PLAZA AUTO PRIMA",
              "PT. PRATAMA MITRA SEJATI",
              "PT. PRIMA INTEGRASI NETWORK",
              "PT. PRIMUS INDONESIA",
              "PT. PROPAN RAYA I.C.C",
              "PT. PUTRA BANGUN CITRA MANDIRI",
              "PT. PYRIDAM FARMA TBK",
              "PT. RAHEL KARYA EMAS",
              "PT. RANOB MEDIA INTERACTIVE",
              "PT. REKA PIRANTI PRAKARSA",
              "PT. RICH PRODUCTS",
              "PT. SARIMURNI JAYA",
              "PT. SIMPATINDO MULTIMEDIA",
              "PT. STANLI TRIJAYA MANDIRI",
              "PT. SUBAGA SURVEI PERSADA",
              "PT. SUMMITRA SOLUSINDO",
              "PT. SUPERNOVA FLEXIBLE",
              "PT. SURYA INTI MANDIRI",
              "PT. TATAMULIA NUSANTARA INDAH",
              "PT. TELEMATIC MULTISYSTEM",
              "PT. TIGA SRIKANDI JAYA",
              "PT. TIRTAKENCANA TATAWARNA",
              "PT. TOSHIBA GLOBAL COMMERCE",
              "PT. TRANS - PACIFIC",
              "PT. TRAVELOKA INDONESIA",
              "PT. TRIBUANA MANUNGGAL",
              "PT. TRIPAR MULTIVISION PLUS",
              "PT. ULTIMA DIGITAL INDONESIA",
              "PT. UPC SIDRAP BAYU ENERGI",
              "PT. YULIE SEKURITAS INDONESIA",
              "PT.ASURANSI FPG INDONESIA",
              "PT.BALISOFT LINTASMEDIA",
              "PT.EKAMAS FORTUNA",
              "PT.HITACHI TERMINAL",
              "PT.JEE TECHNOLOGY INDONESIA",
              "PT.KINERJA UNGGUL NUSANTARA",
              "PT.KREASI SEJAHTERA TEKNOLOGI",
              "PT.MANDIRI TUNAS MUDA",
              "PT.NAGASAKTI PARAMASHOES",
              "PT.TANABE INDONESIA",
              "PUS PENGEMB TEKNOLOGI MINERAL",
              "PUSAT ILMU KOMPUTER UI",
              "PUSAT STATISTIK PENDIDIKAN",
              "REPSOL EXPLORATION CENDRAWASIH",
              "RS JANTUNG HARAPAN KITA",
              "RS TELOGOREJO",
              "RSPAU DR. S. HARDJOLUKITO",
              "RSUP DR.\u00a0SARDJITO\u00a0YOGYAKARTA",
              "RTI INFOKOM PT",
              "RTI INTERNATIONAL",
              "RUMAH SAKIT ANAK DAN",
              "RUMAH SAKIT FATMAWATI",
              "RUMAH SAKIT ISLAM JAKARTA",
              "RUMAH SAKIT METROPOLITAN",
              "RUMAH SAKIT PANTAI INDAH KAPUK",
              "RUMAH SAKIT UMUM HAJI SURABAYA",
              "RUMAHNANGKA.COM",
              "RUMAHWEB",
              "SAMSUNG ELECTRONICS INDONESIA",
              "SANTOSA BANDUNG INTERNATIONAL",
              "SARICO INDAH",
              "SAT KERJA SEMENTARA PELAKSANA",
              "SATYA VISI UTAMA",
              "SEKOLAH PELITA HARAPAN",
              "SEKRETARIAT DPR REPUBLIK",
              "SENAYAN TRIKARYA SEMPANA, PT",
              "SINGAPORE AIRLINES",
              "SISNET MITRA SEJAHTERA PT",
              "SOCLFEED",
              "SOEMADIPRADJA & TAHER",
              "SOLUSI PARAMITRA",
              "SUPERIORPICS",
              "SUZUYA GROUP",
              "TOYOPLAS MFG INDONESIA",
              "TRANS POWER MARINE PT",
              "UNITED NATIONS DEVELOPMENT",
              "UNIV.INDONESIA FAKULTAS HUKUM",
              "UNIV.MUHAMMADIYAH SURAKARTA",
              "UNIVERSITAS ISLAM NEGERI",
              "UNIVERSITAS ISLAM SYEKH YUSUF",
              "UNIVERSITAS MERCU BUANA",
              "UNIVERSITAS MUHAMMADIYAH",
              "UNIVERSITAS NASIONAL FAKULTAS",
              "UNIVERSITAS PASUNDAN",
              "UNIVERSITAS SRIWIJAYA",
              "UNIVERSITAS SUMATERA UTARA",
              "UNIVERSITAS TERBUKA",
              "VALDO INC",
              "VISONINDO NETWORK PERDANA",
              "WACHOVIA BANK, N.A",
              "WAVOO",
              "WEIR MINERALS",
              "WELLS FARGO BANK, N.A",
              "YAYASAN AMIK BANI SALEH"
            ]
          },
          {
            "id": "T0012452",
            "clients": [
              "ALTERMYTH",
              "ARROW ELECTRONICS, INC.",
              "ASKITEL",
              "AT&T WORLDWIDE TELECOMMUNICA-",
              "BADAN NASIONAL PENEMPATAN DAN",
              "BADAN PENGATUR HILIR MINYAK",
              "BADAN PENGEMBANGAN SUMBER DAYA",
              "BADAN STANDARDIDASI NASIONAL",
              "BALAI RISET DAN OBSERVASI",
              "BANDUNG INSTITUTE OF TECHNOLOG",
              "BANK HIMPUNAN SAUDARA",
              "BANK OF CHINA",
              "BANK PERKREDITAN RAKYAT",
              "BANK PINAESAAN",
              "BANPU",
              "BEN LINE AGENCIES",
              "BENDAHARAWAN RUTIN DINAS",
              "BPKP PERWAKILAN PROVINSI JAWA",
              "BPR BKK LASEM",
              "BUT. ABN AMRO BANK N.V",
              "BUT.REPSOL EXPLORACION",
              "CARGILL, INCORPORATED",
              "CHEIL JEDANG INDONESIA, PT",
              "COROUS360, PT",
              "CV TITIPAN KILAT",
              "CV. INDOKOM",
              "CV. MULIA SETIA HATI",
              "D&B INDONESIA PT",
              "DANA PENSIUN PERKEBUNAN PT",
              "DEPARTEMEN KEHAKIMAN RI",
              "DHL EXEL SUPPLY CHAIN",
              "DINAS KEPENDUDUKAN DAN CATATAN",
              "DINAS PENDAPATAN DAERAH TORAJA",
              "DINAS PENDAPATAN DAN PENGELOLA",
              "DINAS PENGELOLAAN KEUANGAN",
              "DINAS PERHUBUNGAN KOMUNIKASI",
              "DIPENDA KODYA PADANG",
              "DIPENDA TK II PEKANBARU",
              "DIPENDA TK.II MOJOKERTO",
              "DISDUS INDONESIA, PT",
              "DISPENDA PROVINSI JAWA BARAT",
              "DPPKAD PEMERINTAH KABUPATEN",
              "EDGE NETWORK SERVICES LIMITED",
              "EKOKAPITAL SEKURITAS, PT",
              "ENESIS GROUP",
              "ERRAENERSI KONSTRUKSINDO, PT",
              "FIRST NATIONAL GLASSWARE LTD",
              "FORESIGHT CONSULTING",
              "GARUDA FOOD GROUP",
              "GDILAB",
              "GEREJA JKI INJIL KERAJAAN",
              "GEREJA MAWAR SHARON",
              "GOLDEN CASTLE, PT",
              "GRAHA ENERGI DELAPAN MANDIRI",
              "GUNATRONIKATAMA CIPTA SISTIM",
              "HD CAPITAL PT",
              "HIMPUNAN BANK MILIK NEGARA",
              "HONEYWELL PTE. LTD,",
              "HOTEL TRIO INDAH",
              "IDWEBHOST",
              "INDO TAMBANGRAYA MEGAH TBK, PT",
              "INDOINTERNIX",
              "INDUSTRI JAMU BOROBUDUR",
              "INSTITUT SENI INDONESIA",
              "JABABEKA",
              "JGC CORPORATION & PT. BRI J.O",
              "JL EMERGING MARKETS",
              "JOHNY ANDREAN GROUP",
              "KAMADJAJA LOGISTICS PT",
              "KANTOR DINAS PENDAPATAN PROV",
              "KANTOR WAKIL PRESIDEN",
              "KEMENTERIAN PERTANIAN REPUBLIK",
              "KISEL INDONESIA",
              "KLIKSAYA.COM",
              "KOTAMINYAK INTERNUSA, PT",
              "KUDO",
              "KWIK KIAN GIE SCHOOL OF",
              "LAPINDO BRANTAS INC",
              "LAUTAN LUAS, PT",
              "MAHKAMAH AGUNG REPUBLIK",
              "MANDALA MULTIFINANCE TBK, PT",
              "MEDIA AKSES GLOBAL INDO",
              "METROPOLITAN MEDICAL CENTER",
              "MILLENIUM CHALLENGE ACCOUNT",
              "MOET-HENNESSY ASIA PTE LTD",
              "NATIONAL HOSPITAL SURABAYA",
              "OPTIK SEIS",
              "P.T. MITSUBISHI JAYA",
              "PD BPR BANK JOGJA",
              "PEMDA TK I BALI",
              "PEMERINTAH KOTA BANDUNG",
              "PERSATUAN AKTUARIS INDONESIA",
              "PERUM PERIKANAN INDONESIA",
              "POLITEKNIK KAMPAR",
              "POLITEKNIK NEGERI SEMARANG",
              "PRESIDENCY OF THE REPUBLIC OF",
              "PRIMA PARAHYANGAN COMPUTER",
              "PRIMACOM INTERBUANA, PT",
              "PRIMATAMA KARYA PERSADA, PT",
              "PT  SEKAR BUMI TBK",
              "PT ACEH RUBBER INDUSTRIES",
              "PT ADHYA TIRTA BATAM",
              "PT ADSKOM INDONESIA",
              "PT ADYABINA PUTRAMAS",
              "PT AGRO HARAPAN LESTARI",
              "PT AIRINDO SAKTI",
              "PT AJINOMOTO INDONESIA",
              "PT ALCAN INDONESIA",
              "PT ALIANSI TEKNOLOGI INDONESIA",
              "PT ANUGERAH ARGONMEDICA",
              "PT ANUGERAH PHARMINDO LESTARI",
              "PT ANWAR SIERAD",
              "PT APAC INTI CORPORA",
              "PT ARAH INVESTASI MANDIRI",
              "PT ARDH GLOBAL INDONESIA",
              "PT ARGHA KARYA PRIMA INDUSTRY",
              "PT ARISTI JASADATA",
              "PT ARNOTT'S INDONESIA",
              "PT ASMO INDONESIA",
              "PT ASTRAZENECA INDONESIA",
              "PT ASURANSI BINA DANA ARTA TBK",
              "PT ASURANSI JIWA INDOSURYA",
              "PT ATEJA TRITUNGGAL",
              "PT AUSTASIA STOCKFEED",
              "PT AUSTINDO NUSANTARA JAYA TBK",
              "PT BAKRIE & BROTHERS",
              "PT BALINA AGUNG PERKASA",
              "PT BANK AKITA",
              "PT BANK MALUKU",
              "PT BANK PACIFIC",
              "PT BANK RABOBANK INTERNATIONAL",
              "PT BANK UFJ INDONESIA",
              "PT BELAMANI INTI UTAMA",
              "PT BERLINA TBK",
              "PT BHAKTI FINANCE",
              "PT BIMA SENOPATI GROGOL",
              "PT BLUE CUBE INDONESIA",
              "PT BPR JAWA TIMUR",
              "PT BPR SURYA YUDHA KENCANA",
              "PT BRAVURA BISNIS SOLUSI",
              "PT BUKIT JAYA ABADI",
              "PT BUKIT PERAK",
              "PT BUMBU DESA",
              "PT CAHAYA BINTANG MANDIRI",
              "PT CAKRAWALA ANDALAS TELEVISI",
              "PT CAPRIFARMINDO LABORATORIES",
              "PT CATUR MITRA SEJATI SENTOSA",
              "PT CENTRAL RETAIL INDONESIA",
              "PT CHEIL JEDANG INDONESIA",
              "PT CIPTA TELEVISI PENDIDIKAN",
              "PT CIPTADANA CAPITAL",
              "PT CISADANE RAYA CHEMICALS",
              "PT CITRA ABADI SEJATI",
              "PT CITRA SARI MAKMUR",
              "PT DAMAI SEJATI",
              "PT DATACOM DIANGRAHA",
              "PT DJABESMEN",
              "PT DONGSUNG JAKARTA",
              "PT EGLOBAL TEKNOLOGI SOLUSINDO",
              "PT ELMARA REZEKI UTAMA",
              "PT EPCOS INDONESIA",
              "PT ESPAY DEBIT INDONESIA",
              "PT ETERNIT GRESIK",
              "PT EWINDO",
              "PT EXCO NUSANTARA INDONESIA",
              "PT EXPEDITORS INDONESIA",
              "PT FASTRATA BUANA",
              "PT FORTUNE INDONESIA",
              "PT FRISIAN FLAG INDONESIA",
              "PT FUJITSU SYSTEMS INDONESIA",
              "PT GALIC BINA MADA",
              "PT GARUDA METALINDO",
              "PT GENERAL MOTORS INDONESIA",
              "PT GENERASI INDONESIA DIGITAL",
              "PT GENTRANS INDONESIA",
              "PT GEOTHERMAL SERVICES",
              "PT GM AUTO WORLD INDONESIA",
              "PT GOBEL DHARMA NUSANTARA",
              "PT GREEN EAGLE",
              "PT GUNATRONIKATAMA CIPTA",
              "PT GUNTNER INDONESIA",
              "PT HAGA BANK",
              "PT HARITA PANCA UTAMA",
              "PT HARITA PRIMA ABADI MINERAL",
              "PT HARTONO ISTANA TEKNOLOGI",
              "PT HARTONO WIRA TANIK",
              "PT HASJRAT ABADI",
              "PT HERCULON CARPET",
              "PT HI-TECH AGRATEKTRON",
              "PT HONEY LADY UTAMA",
              "PT INDO AD",
              "PT INDO TAMBANGRAYA MEGAH TBK",
              "PT INDOINTERNET",
              "PT INDOMINCO MANDIRI",
              "PT INDONESIA NEWS CENTER",
              "PT INDONUSA COMPUTER SYSTEM",
              "PT INDOPRIMA GEMILANG",
              "PT INDO-RAMA SYNTHETICS TBK",
              "PT INDRA BISMA MAHESA",
              "PT INFINYS SYSTEM INDONESIA",
              "PT INOVASI LINTAS MEDIA",
              "PT INTER ANEKA LESTARI KIMIA",
              "PT INTER-DELTA",
              "PT INTERNA PRIMA",
              "PT INTI DUFREE PROMOSINDO",
              "PT INTI GANDA PERDANA",
              "PT JAKARTA LAND",
              "PT JASA TEKNOLOGI",
              "PT JATIMWOOD KARYAJAYA",
              "PT JC INDONESIA",
              "PT JOJONOMIC INDONESIA",
              "PT JONES LANG LASALLE",
              "PT JORONG BARUTAMA GRESTON",
              "PT KABELMETAL INDONESIA",
              "PT KAMALTEX/TUBANTIA",
              "PT KAPAL API GLOBAL",
              "PT KITADIN",
              "PT KLIRING BERJANGKA INDONESIA",
              "PT KONSULINDO INFORMATIKA",
              "PT KRESNA ASSET MANAGEMENT",
              "PT KRIDATAMA LANCAR",
              "PT KUBOTA INDONESIA",
              "PT LAFARGE CEMENT ANDALAS",
              "PT LAUTANDHANA SECURINDO",
              "PT LEA SANENT",
              "PT LIFUNG INDONESIA",
              "PT LIMAWIRA WISESA",
              "PT LINFOX LOGISTICS INDONESIA",
              "PT LUMBUNG ARTAKENCANA",
              "PT MAERSK INDONESIA",
              "PT MAERSK INDONESIA FOR MAERSK",
              "PT MAHACITTA TEKNOLOGI",
              "PT MARUBENI INDONESIA",
              "PT MASAGUNG TUNGGAL",
              "PT MASTANDO EKARAKSA",
              "PT MATAHARI SAKTI",
              "PT MAXIMA INTEGRA INVESTAMA",
              "PT MAZDA INDONESIA MFG",
              "PT MAZDA MOTOR INDONESIA",
              "PT MEDIATRAC SISTEM KOMUNIKASI",
              "PT METROCOM GLOBAL SOLUSI",
              "PT MISYS INTERNATIONAL",
              "PT MITRA ANUGERAH GEMILANG",
              "PT MITRA BISINFO UTAMA",
              "PT MITRA LINGKUNGAN",
              "PT MITRA SARANA PURNAMA",
              "PT MODERN PHOTO FILM CO",
              "PT MORGAN STANLEY ASIA",
              "PT MULTISOFT JAVA TECHNOLOGIES",
              "PT MUSTIKA RATU",
              "PT MUTIARA BARA ENERGY",
              "PT NETMARKS INDONESIA",
              "PT NEWMONT NUSA TENGGARA",
              "PT NORTHSTAR PACIFIC CAPITAL",
              "PT NUSA HALMAHERA MINERALS",
              "PT OPTUS SOLUTION",
              "PT ORINDO ALAM AYU (ORIFLAME)",
              "PT OTP GEOTHERMAL SERVICES",
              "PT PACIFIC AGUNG TRIJAYA",
              "PT PACIFIC PLACE JAKARTA",
              "PT PANALPINA NUSAJAYA",
              "PT PANGANSARI UTAMA",
              "PT PAPERTECH INDONESIA",
              "PT PASARAYA NUSAKARYA",
              "PT PCI ELEKTRONIK",
              "PT PELITA RELIANCE",
              "PT PERKEBUNAN XII",
              "PT PHINCON",
              "PT POS INDONESIA (PERSERO)",
              "PT PRADJA PHARMACEUTICAL",
              "PT PRICE WATERHOUSE INDONESIA",
              "PT PRICEBOOK DIGITAL INDONESIA",
              "PT PRIMA ALLOY STEEL",
              "PT PRIMA INREKSA INDUSTRIES",
              "PT PROCTER & GAMBLE HOME",
              "PT PUNDI KENCANA",
              "PT RABO BANK DUTA INDONESIA",
              "PT RAJA KAMAR INTERNATIONAL",
              "PT RAJAWALI PLANTATION",
              "PT RELIANCE SECURITIES",
              "PT RINTIS SEJAHTERA",
              "PT ROYAL ABADI SEJAHTERA",
              "PT SAMUDERA INFORMASI",
              "PT SANGGAR SARANA BAJA",
              "PT SANTAN BATUBARA",
              "PT SAP INDONESIA",
              "PT SARANAGRIYA LESTARI KERAMIK",
              "PT SARANAKREASI TEKNOLOGI",
              "PT SCHNEIDER INDONESIA",
              "PT SEBUKU IRON LATERITIC ORES",
              "PT SEPATU BATA",
              "PT SHINDENGEN INDONESIA",
              "PT SIEMENS INDONESIA",
              "PT SILVERLAKE INFORMATIKATAMA",
              "PT SISTELINDO MITRA LINTAS",
              "PT SOFCO GRAHA",
              "PT SORINI TOWA BERLIAN",
              "PT SRI TRANG LINGGA INDONESIA",
              "PT SRIBOGA RATURAYA SEMARANG",
              "PT STRUCTURED SERVICES",
              "PT SUCORINVEST CENTRAL GANI",
              "PT SUMCO INDONESIA",
              "PT SUPRA PRIMATAMA NUSANTARA",
              "PT SUPREME CABLE MFG CORP",
              "PT SURACO JAYA ABADI MOTOR",
              "PT SURVEY PRIMA SOLUSI",
              "PT SURYA GEMILANG PERKASA",
              "PT SURYA MULTI INDOPACK",
              "PT SURYA PERTIWI",
              "PT SURYA SEMESTA INTERNUSA TBK",
              "PT SWAKARSA SINARSENTOSA",
              "PT SYNNEX METRODATA INDONESIA",
              "PT TAP APPLIED AGRI SERVICES",
              "PT TIETOENATOR INDONESIA",
              "PT TIP TOP",
              "PT TIRTA ALAM SEGAR",
              "PT TIRTA PUTRA WISATA",
              "PT TITAN PETROKIMIA NUSANTARA",
              "PT TOTAL OIL INDONESIA",
              "PT TRANS AVIA UTAMA",
              "PT TRIPUTRA AGRO PERSADA",
              "PT TRUBAINDO COAL MINING",
              "PT TUDUNG PUTRA PUTRI JAYA",
              "PT UNICHEM CANDI INDUSTRI DURI",
              "PT UNIPACK INDOSYSTEMS",
              "PT VALBURY ASIA FUTURES",
              "PT VIVA MEDIA BARU",
              "PT VIVASTOR TECHNO LOGICA",
              "PT VOLEX CABLE ASSEMBLY",
              "PT WILMAR CONSULTANCY SERVICES",
              "PT WIRATMAN & ASSOCIATES",
              "PT WIRELESS INDONESIA",
              "PT XSYS DISTI CEMERLANG",
              "PT. 88DB INDONESIA",
              "PT. AETRA AIR TANGERANG",
              "PT. AJINOMOTO INDONESIA",
              "PT. ALAM JAYA PRIMANUSA",
              "PT. ALFA OMEGA INDUSTRI",
              "PT. ASIASOFT INDONESIA",
              "PT. ASSAFAR IMAN AMANAH",
              "PT. ASURANSI MAXIMUS GRAHA",
              "PT. ATLAS COPCO INDONESIA",
              "PT. AUTOMOTIVE FASTENERS",
              "PT. BAKER HUGHES INDONESIA",
              "PT. BELCINDO SINAR MULIA",
              "PT. BETON PERKASA WIJAKSANA",
              "PT. BIRU AMRETA TRISNA",
              "PT. BOSOWA CORPORINDO",
              "PT. CLADTEK BI METAL",
              "PT. COSMA MITRA SEJAHTERA",
              "PT. CRIF LEMBAGA INFORMASI",
              "PT. DATACOMM DIANGRAHA",
              "PT. DHARMA AGUNG WIJAYA",
              "PT. EBIZ CIPTA SOLUSI",
              "PT. ECOGREEN OLEOCHEMICALS",
              "PT. EGLOBAL TEKNOLOGI",
              "PT. ENERGI MITRA INVESTAMA",
              "PT. ENERGY CONSULTING",
              "PT. EUROKARS ARTHA UTAMA",
              "PT. EZEELINK INDONESIA",
              "PT. FAIRCO AGRO MANDIRI",
              "PT. FAJAR INTI SURYA",
              "PT. FINNANTARA INTIGA",
              "PT. FUTURE PIPE INDUSTRIES",
              "PT. GENERAL MOTORS INDONESIA",
              "PT. GML PERFORMANCE CONSULTING",
              "PT. GORONTALO PG",
              "PT. INDOGOLD SOLUSI GADAI",
              "PT. INDOJAYA AGRINUSA",
              "PT. INDUSTRI DJAMU DAN",
              "PT. IONSOFT",
              "PT. ITHACA RESOURCES",
              "PT. JAYA TEKNIK INDONESIA",
              "PT. JGC CORPORATION & PT JGC",
              "PT. KALVENTIS SINERGI FARMA",
              "PT. KARYAMAS ADINUSANTARA",
              "PT. KARYAMEGAH ADIJAYA",
              "PT. KEMALA INTI SOLUSI",
              "PT. KORN/FERRY INTERNATIONAL",
              "PT. KREON INDONESIA",
              "PT. MARUNDA MEGA INDUSTRI",
              "PT. MASTERCARD INDONESIA",
              "PT. MEGA INFOTAMA",
              "PT. MINDA ASEAN AUTOMOTIVE",
              "PT. NEC INDONESIA",
              "PT. NORTHSTAR PACIFIC CAPITAL",
              "PT. PELAYARAN BINTANG PUTIH",
              "PT. PFI MEGA LIFE INSURANCE",
              "PT. POLYFIN CANGGIH",
              "PT. PRASADHA PAMUNAH",
              "PT. PSN ENAM INDONESIA",
              "PT. RAJA ABADI MAKMUR SEJATI",
              "PT. RSM INDONESIA KONSULTAN",
              "PT. SANDVIK INDONESIA",
              "PT. SEMBILAN PILAR ANUGERAH",
              "PT. SHELL INDONESIA",
              "PT. SIEMENS INDUSTRIAL POWER",
              "PT. SIRA MANUNGGAL SELARAS",
              "PT. SISINDOKOM LINTASBUANA",
              "PT. SRITRANG LINGGA INDONESIA",
              "PT. STAR CONCORD INDONESIA",
              "PT. SUNINDO KOOKMIN",
              "PT. TANI HUB INDONESIA",
              "PT. TARUNAKUSUMA PURINUSA",
              "PT. TEKNOLAND MITRA SOLUSI",
              "PT. TERA TEKNO INFOTAMA",
              "PT. TOTAL BANGUN PERSADA TBK",
              "PT. TRAFOINDO PRIMA PERKASA",
              "PT. TRANS HAMANA TEKNOLOGI",
              "PT. UNGGUL KARSA MEDIKA",
              "PT. VICTORIA CARE INDONESIA",
              "PT. WARU GUNUNG INDUSTRY",
              "PT. WIKARAGA SAPTAUTAMA",
              "PT. WORLDLINE INTERNATIONAL",
              "PT. ZEBRA ASABA INDUSTRI",
              "PT.ACCLIVIS TECHNOLOGIES",
              "PT.BANK MITRANIAGA",
              "PT.CIRCLES TEKNOLOGI INDONESIA",
              "PT.EXERTAINMENT INDONESIA",
              "PT.JEMBO CABLE COMPANY TBK",
              "PT.PATCO ELEKTRONIK TEKNOLOGI",
              "PT.PERMATA ANUGERAH ABADI",
              "PT.SARANA MAJU LESTARI",
              "PT.SENTRA USAHATAMA JAYA",
              "PT.SULFINDO ADIUSAHA",
              "PUSAT KOMPUTER ITB",
              "PUSAT PELAPORAN DAN ANALISIS",
              "PUSLITBANG IONOSFER LAPAN",
              "PUSLITBANG JALAN DAN JEMBATAN",
              "RAMBA ENERGY, PT",
              "REKA PIRANTI PRAKARSA, PT",
              "REPEX WAHANA PT",
              "RIAU INVESTMENT CORP",
              "RS AWAL BROS",
              "RS HUSADA",
              "RSB BUNDA",
              "RSUD DR. SOEBANDI",
              "RSUP CIPTO MANGUNKUSUMO",
              "RSUP DR. KARIADI",
              "RUMAH SAKIT AKADEMIK",
              "RUMAH SAKIT FATMAWATI JAKARTA",
              "RUMAH SAKIT GRHA KEDOYA",
              "RUMAH SAKIT MEDIKA PERMATA",
              "RUMAH SAKIT UMUM DAERAH KOTA",
              "RUMAH TANGGA KEPRESIDENAN",
              "SEKJEN DPR RI BIDANG DATA DAN",
              "SEKRETARIAT NEGARA RI",
              "SEKRETARIAT WAKIL PRESIDEN",
              "SEMEN BOSOWA MAROS, PT",
              "SHANGRI-LA HOTEL",
              "SHANGRI-LA RESIDENCES",
              "SHARP SEMICONDUCTOR INDONESIA",
              "SILVERLAKE STRUCTURED",
              "SKK MIGAS",
              "SOFTEX INDONESIA PT",
              "SOMERSET SURABAYA HOTEL AND",
              "STEGGI BERSAUDARA",
              "STIE PERBANAS",
              "SUNGAI BUDI GROUP",
              "SUNSTAR ENGINEERING INDONESIA",
              "SURYA MULIA INTERNATIONAL",
              "TANJUNG JATI B, PT",
              "TATELY N.V",
              "TIGA PILAR SEJAHTERA, PT",
              "TIKI JALUR NUGRAHA EKAKURIR PT",
              "TOPJAYA SARANA UTAMA",
              "TOTAL E & P INDONESIE",
              "TOTAL INDONESIE JAKARTA",
              "TOUCHTEN PTE LTD",
              "TRANSPORTASI JAKARTA",
              "UIN SUNAN KALIJAGA",
              "UNIVERSITAS BUDI LUHUR",
              "UNIVERSITAS ISLAM NEGERI",
              "UNIVERSITAS KRISTEN KRIDA",
              "UNIVERSITAS MUHAMMADIYAH",
              "UNIVERSITAS NEGERI SURABAYA",
              "UNIVERSITAS PENDIDIKAN",
              "UNIVERSITAS PERSADA INDONESIA",
              "UNIVERSITAS PERTAHANAN",
              "UNIVERSITAS SYIAH KUALA",
              "UNIVERSITAS TRILOGI",
              "UNIVERSITAS TRISAKTI",
              "URUNAN (981193)",
              "WMGS S'PORE PTE LTD REPS OFF",
              "WOORI KORINDO SECURITIES",
              "Y. EKO PURWANTO",
              "YAY. ADI UPAYA",
              "YAY. UNIVERSITAS KRISTEN",
              "YAYASAN PENDIDIKAN GUNADARMA",
              "Grand Total"
            ]
          }
        ]
      }
    ]
  };

  const filteredResults = searchTerm ? 
    data.squads.flatMap(squad =>
      squad.groups.flatMap(group =>
        group.clients
          .filter(client => 
            client.toLowerCase().includes(searchTerm.toLowerCase())
          )
          .map(client => ({
            client,
            squad: squad.name,
            group: group.id
          }))
      )
    ) : [];

  return (
    <Card className="w-full max-w-3xl mx-auto p-4">
      <CardHeader>
        <CardTitle className="text-2xl font-bold text-center mb-6">
          Client Squad Search
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="relative mb-6">
          <Search className="absolute left-2 top-2.5 h-4 w-4 text-gray-500" />
          <Input
            type="text"
            placeholder="Search for a client..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-8"
          />
        </div>

        <div className="space-y-4">
          {filteredResults.map((result, index) => (
            <div 
              key={index} 
              className="p-4 border rounded-lg hover:bg-gray-50 transition-colors"
            >
              <h3 className="font-medium text-lg">{result.client}</h3>
              <div className="mt-2 text-sm text-gray-600">
                <p>Squad: {result.squad}</p>
                <p>Group: {result.group}</p>
              </div>
            </div>
          ))}
          
          {searchTerm && filteredResults.length === 0 && (
            <div className="text-center text-gray-500 py-8">
              No clients found matching "{searchTerm}"
            </div>
          )}
          
          {!searchTerm && (
            <div className="text-center text-gray-500 py-8">
              Type to search for clients
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default ClientSquadSearch;